[mypy]
python_version = 3.12
ignore_errors = True
ignore_missing_imports = true
follow_untyped_imports = false
explicit_package_bases = true
mypy_path = "src,."
plugins = pydantic.mypy, pandera.mypy

