"""
English diplomatic lexicon for BB-PAXDATA.

Provides:
- DIPLO_LEXICON_EN: Sentiment scores for English diplomatic vocabulary
- NEGATION_WORDS_EN: English negation markers

Scoring convention (same as Turkish DIPLO_LEXICON_TR):
    Positive values → cooperative/constructive diplomatic tone
    Negative values → confrontational/aggressive diplomatic tone
    Range: [-1.0, 1.0]

Note:
    This lexicon covers ~150 high-priority English diplomatic terms.
    Scores are aligned with diplomatic usage patterns in international relations.
"""

# ---------------------------------------------------------------------------
# English Diplomatic Sentiment Lexicon
# ---------------------------------------------------------------------------

DIPLO_LEXICON_EN: dict[str, float] = {
    # Extreme Negative (-0.7 to -0.9)
    "genocide": -0.8,
    "massacre": -0.8,
    "war crime": -0.7,
    "crime against humanity": -0.8,
    "terrorism": -0.7,
    "terrorist": -0.7,
    "terror": -0.7,
    "premeditated starvation": -0.8,
    "imperial collapse": -0.7,
    "strongly condemn": -0.6,
    "unacceptable": -0.5,
    # Strong Negative (-0.5 to -0.6)
    "aggression": -0.6,
    "aggressive": -0.6,
    "aggressor": -0.6,
    "chemical weapons": -0.6,
    "starvation": -0.6,
    "famine": -0.6,
    "apartheid": -0.6,
    "ontological rot": -0.6,
    "atrocity": -0.6,
    "immense destruction": -0.6,
    "destruction": -0.6,
    "unprovoked": -0.6,
    "war": -0.6,
    "devastating war": -0.6,
    "senseless war": -0.6,
    "sovereignty violation": -0.6,
    "territorial violation": -0.6,
    "threat of force": -0.6,
    "illegal annexation": -0.6,
    "coup": -0.5,
    "occupation": -0.5,
    "hegemony": -0.5,
    "siege": -0.5,
    "proxy war": -0.5,
    "proxy conflict": -0.5,
    "tragedy": -0.5,
    "casualties": -0.5,
    "martyrs": -0.5,
    "suffering": -0.5,
    "displacement": -0.5,
    "refugees": -0.5,
    "impunity": -0.5,
    "blackmail": -0.5,
    "repressive": -0.5,
    "border violation": -0.5,
    "cyber warfare": -0.5,
    "blockade": -0.5,
    "hostilities": -0.5,
    "hostility": -0.5,
    "provocative acts": -0.5,
    # Mid Negative (-0.3 to -0.4)
    "deadlock": -0.4,
    "impasse": -0.4,
    "double standards": -0.4,
    "disinformation": -0.4,
    "conflict": -0.4,
    "failed": -0.4,
    "extremism": -0.4,
    "fragmentation": -0.4,
    "cyberattack": -0.4,
    "polarization": -0.4,
    "escalation": -0.4,
    "unilateral actions": -0.4,
    "economic sanction": -0.4,
    "military buildup": -0.4,
    "regional instability": -0.4,
    "crisis": -0.4,
    "condemn": -0.4,
    "sanction": -0.3,
    "sanctions": -0.3,
    "tension": -0.3,
    "threat": -0.3,
    "instability": -0.3,
    "unstable": -0.3,
    "turbulent": -0.3,
    "unpredictable": -0.3,
    "boycott": -0.3,
    "injustice": -0.3,
    "deep concern": -0.3,
    "territorial claim": -0.3,
    # Low Negative (-0.1 to -0.2)
    "dependence": -0.2,
    "uncertainty": -0.2,
    "concern": -0.2,
    "zero-sum": -0.2,
    "fatigue": -0.2,
    "fragile": -0.1,
    # Extreme Positive (+0.6 to +0.8)
    "comprehensive peace": 0.7,
    "just peace": 0.6,
    "peace": 0.6,
    "peaceful coexistence": 0.6,
    "non-aggression": 0.6,
    "global solidarity": 0.6,
    "peaceful resolution": 0.6,
    # Strong Positive (+0.4 to +0.5)
    "strategic partnership": 0.5,
    "anticipatory leadership": 0.5,
    "ceasefire": 0.5,
    "consensus": 0.5,
    "radical inclusion": 0.5,
    "reconciliation": 0.5,
    "prosperity": 0.5,
    "dialogue": 0.5,
    "negotiations": 0.5,
    "shared responsibility": 0.5,
    "cooperation": 0.5,
    "partnership": 0.5,
    "solidarity": 0.5,
    "mutual respect": 0.4,
    "confidence-building measures": 0.4,
    "confidence-building": 0.4,
    "security guarantees": 0.4,
    "constructive dialogue": 0.4,
    "disarmament": 0.4,
    "accountability": 0.4,
    "integration": 0.4,
    "normalization": 0.4,
    "sovereignty": 0.4,
    "diplomatic": 0.4,
    "mediation": 0.4,
    "mediator": 0.4,
    "de-escalation": 0.4,
    "de-escalate": 0.4,
    "collective security": 0.4,
    "human rights": 0.4,
    "humanitarian aid": 0.4,
    "territorial integrity": 0.4,
    "win-win": 0.4,
    # Mid Positive (+0.2 to +0.3)
    "multilateral": 0.3,
    "multilateralism": 0.3,
    "multipolarity": 0.3,
    "resilience": 0.3,
    "inclusive": 0.3,
    "prevention": 0.3,
    "connectivity": 0.3,
    "deterrence": 0.3,
    "neutrality": 0.3,
    "reform": 0.2,
    "agreement": 0.2,
    "treaty": 0.2,
    "diplomatic effort": 0.3,
    "diplomatic relations": 0.3,
    "bilateral relations": 0.2,
    "constructive engagement": 0.3,
    "goodwill": 0.3,
    "humanitarian corridor": 0.3,
    "consensus building": 0.3,
    "stability": 0.3,
    "stable": 0.3,
    "stabilization": 0.3,
    "sovereign equality": 0.3,
    "sustainable solution": 0.3,
    "sustainable development": 0.3,
    "joint declaration": 0.3,
    "memorandum of understanding": 0.3,
    "facilitator": 0.3,
    # Low Positive (+0.1)
    "transition": 0.1,
}

# ---------------------------------------------------------------------------
# English Negation Words
# ---------------------------------------------------------------------------

NEGATION_WORDS_EN: frozenset[str] = frozenset(
    {
        "not",
        "no",
        "never",
        "none",
        "nothing",
        "neither",
        "nowhere",
        "without",
        "lack",
        "lacks",
        "lacking",
        "lacked",
        "absent",
        "absence",
        "deny",
        "denies",
        "denied",
        "reject",
        "rejects",
        "rejected",
        "refuse",
        "refuses",
        "refused",
        "oppose",
        "opposes",
        "opposed",
        "against",
        "anti",
        "counter",
        "dis",
        "mis",
        "in",
        "im",
        "il",
        "ir",
        "un",
        "cannot",
        "can't",
        "couldn't",
        "wouldn't",
        "shouldn't",
        "mustn't",
        "mightn't",
        "needn't",
        "don't",
        "doesn't",
        "didn't",
        "won't",
        "isn't",
        "aren't",
        "wasn't",
        "weren't",
        "haven't",
        "hasn't",
        "hadn't",
    }
)
