"""
Turkish stopword list for BB-PAXDATA.

Stopwords are high-frequency function words that carry minimal
semantic information for diplomatic sentiment analysis.

Source: Compiled from standard Turkish NLP resources,
filtered for diplomatic transcript context.
"""

STOPWORDS_TR: frozenset[str] = frozenset(
    {
        # Pronouns
        "ben",
        "sen",
        "o",
        "biz",
        "siz",
        "onlar",
        "bu",
        "şu",
        "bunlar",
        "şunlar",
        "kendisi",
        "kendileri",
        # Articles / determiners
        "bir",
        "birkaç",
        "bazı",
        "her",
        "hiçbir",
        "tüm",
        "bütün",
        # Conjunctions
        "ve",
        "veya",
        "ya",
        "ya da",
        "ile",
        "ama",
        "fakat",
        "lakin",
        "ancak",
        "oysa",
        "oysa ki",
        "çünkü",
        "ki",
        "eğer",
        "şayet",
        "hem",
        "hem de",
        "ne",
        "ne de",
        # Prepositions / postpositions (common forms)
        "için",
        "kadar",
        "gibi",
        "göre",
        "karşı",
        "üzere",
        "sonra",
        "önce",
        "arasında",
        "içinde",
        "dışında",
        "üzerinde",
        "altında",
        "yanında",
        "hakkında",
        "konusunda",
        # Common auxiliary verbs (inflected)
        "var",
        "yok",
        "olan",
        "olarak",
        "olmuş",
        "olacak",
        "oldu",
        "olur",
        "olmak",
        "edilmiş",
        "edilmektedir",
        "etmek",
        "etmiş",
        # High-frequency adverbs
        "de",
        "da",
        "dahi",
        "bile",
        "sadece",
        "yalnızca",
        "çok",
        "az",
        "daha",
        "en",
        "oldukça",
        "hala",
        "artık",
        "zaten",
        "ise",
        "iken",
        "böylece",
        "bu nedenle",
        "bu yüzden",
        "dolayısıyla",
        "ayrıca",
        "bunun yanı sıra",
        # Interrogative words
        "kim",
        "nerede",
        "neden",
        "nasıl",
        "hangi",
        "kaç",
        "ne zaman",
        # Common diplomatic filler phrases (low semantic weight)
        "sayın",
        "değerli",
        "ekselansları",
        "efendim",
    }
)
