"""add_country_network_entities

Revision ID: 050ff3fd782c
Revises: 9652d437d1c3
Create Date: 2026-05-15 14:49:06.617407

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "050ff3fd782c"
down_revision: Union[str, None] = "9652d437d1c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legacy_country_references",
        sa.Column("ref_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("sentiment_context", sa.Float(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("ref_id"),
    )
    with op.batch_alter_table("legacy_country_references", schema=None) as batch_op:
        batch_op.create_index("idx_legacy_coref_from", ["from_country"], unique=False)
        batch_op.create_index("idx_legacy_coref_to", ["to_country"], unique=False)

    op.create_table(
        "bilateral_sentiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("from_country", sa.String(length=100), nullable=False),
        sa.Column("to_country", sa.String(length=100), nullable=False),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("interaction_count", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=20), nullable=False),
        sa.Column("affinity_score", sa.Float(), nullable=False),
        sa.Column("power_weighted_score", sa.Float(), nullable=False),
        sa.Column("diplomatic_distance", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bilateral_sentiments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_bs_panel_pair", ["panel_id", "from_country", "to_country"], unique=True
        )

    op.create_table(
        "country_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("speaker_country", sa.String(length=100), nullable=False),
        sa.Column("referenced_country", sa.String(length=100), nullable=False),
        sa.Column("sentence_index", sa.Integer(), nullable=False),
        sa.Column("reference_context", sa.String(length=50), nullable=False),
        sa.Column("raw_sentiment_score", sa.Float(), nullable=False),
        sa.Column("speaker_power_level", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.create_index("ix_cr_panel_id", ["panel_id"], unique=False)
        batch_op.create_index(
            "ix_cr_speaker_referenced",
            ["speaker_country", "referenced_country"],
            unique=False,
        )

    op.create_table(
        "discourse_flows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("from_country", sa.String(length=100), nullable=False),
        sa.Column("to_country", sa.String(length=100), nullable=False),
        sa.Column("edge_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("sentiment_toward", sa.Float(), nullable=False),
        sa.Column("confrontational_count", sa.Integer(), nullable=False),
        sa.Column("cooperative_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discourse_flows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_df_from_to", ["from_country", "to_country"], unique=False
        )
        batch_op.create_index("ix_df_panel_id", ["panel_id"], unique=False)

    op.create_table(
        "topic_matrices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("topic_scores", sqlite.JSON(), nullable=False),
        sa.Column("dominant_topic", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_matrices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tm_panel_country", ["panel_id", "country"], unique=True
        )

    op.drop_table("_alembic_tmp_ai_demand_analysis")
    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_insight", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_insight_version", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("insight_generated_at", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backend", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("model_name", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_sentiment", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_emotion", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_risk_score", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("ai_risk_level", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_demand_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_topic", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_hedging_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_frame_type", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("ai_manipulation_score", sa.Float(), nullable=True)
        )
        batch_op.add_column(sa.Column("ai_politeness_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_evidence_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("logic_result", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("validation_flags", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("raw_response", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("tokens_used", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("latency_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("anomaly_types", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("anomaly_severity", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "risk_level",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"
            ),
            existing_nullable=True,
        )
        batch_op.drop_index(batch_op.f("idx_ai_sent_prompt_ver"))

    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.alter_column(
            "relationship_type",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "ALLY",
                "ADVERSARY",
                "PARTNER",
                "CAUTIOUS",
                "NEUTRAL",
                name="relationshiptype",
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("panels", schema=None) as batch_op:
        batch_op.drop_column("replaced_by_panel_id")
        batch_op.drop_column("is_active")

    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_time", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("end_time", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duration", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_analyzed", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("logic_result", sa.Text(), nullable=True))
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("logic_result")
        batch_op.drop_column("ai_analyzed")
        batch_op.drop_column("duration")
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    with op.batch_alter_table("panels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.INTEGER(), server_default=sa.text("1"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("replaced_by_panel_id", sa.TEXT(), nullable=True))

    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.alter_column(
            "relationship_type",
            existing_type=sa.Enum(
                "ALLY",
                "ADVERSARY",
                "PARTNER",
                "CAUTIOUS",
                "NEUTRAL",
                name="relationshiptype",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_ai_sent_prompt_ver"), ["prompt_version"], unique=False
        )
        batch_op.alter_column(
            "risk_level",
            existing_type=sa.Enum(
                "NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("anomaly_severity")
        batch_op.drop_column("anomaly_types")
        batch_op.drop_column("latency_ms")
        batch_op.drop_column("tokens_used")
        batch_op.drop_column("raw_response")
        batch_op.drop_column("validation_flags")
        batch_op.drop_column("logic_result")
        batch_op.drop_column("ai_evidence_type")
        batch_op.drop_column("ai_politeness_score")
        batch_op.drop_column("ai_manipulation_score")
        batch_op.drop_column("ai_frame_type")
        batch_op.drop_column("ai_hedging_score")
        batch_op.drop_column("ai_topic")
        batch_op.drop_column("ai_demand_type")
        batch_op.drop_column("ai_risk_level")
        batch_op.drop_column("ai_risk_score")
        batch_op.drop_column("ai_emotion")
        batch_op.drop_column("ai_sentiment")
        batch_op.drop_column("model_name")
        batch_op.drop_column("backend")

    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.drop_column("insight_generated_at")
        batch_op.drop_column("ai_insight_version")
        batch_op.drop_column("ai_insight")

    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    op.create_table(
        "_alembic_tmp_ai_demand_analysis",
        sa.Column("ai_demand_id", sa.INTEGER(), nullable=False),
        sa.Column("demand_id", sa.INTEGER(), nullable=True),
        sa.Column("sent_id", sa.VARCHAR(), nullable=True),
        sa.Column("seg_id", sa.TEXT(), nullable=True),
        sa.Column("panel_id", sa.TEXT(), nullable=True),
        sa.Column("speaker_name", sa.TEXT(), nullable=True),
        sa.Column("country", sa.TEXT(), nullable=True),
        sa.Column("power_level", sa.INTEGER(), nullable=False),
        sa.Column("demand_verb", sa.TEXT(), nullable=True),
        sa.Column("demand_type", sa.TEXT(), nullable=True),
        sa.Column("demand_category", sa.VARCHAR(length=21), nullable=True),
        sa.Column("future_risk", sa.TEXT(), nullable=True),
        sa.Column("risk_severity", sa.INTEGER(), nullable=True),
        sa.Column("demand_subtext", sa.TEXT(), nullable=True),
        sa.Column("hidden_agenda", sa.TEXT(), nullable=True),
        sa.Column("potential_response", sa.TEXT(), nullable=True),
        sa.Column("escalation_path", sa.TEXT(), nullable=True),
        sa.Column("diplomatic_leverage", sa.TEXT(), nullable=True),
        sa.Column("future_demands", sa.TEXT(), nullable=True),
        sa.Column("strategic_value", sa.FLOAT(), nullable=True),
        sa.Column("backend_used", sa.TEXT(), nullable=True),
        sa.Column("model_used", sa.TEXT(), nullable=True),
        sa.Column("processing_ms", sa.INTEGER(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("prompt_version", sa.VARCHAR(length=80), nullable=True),
        sa.ForeignKeyConstraint(
            ["demand_id"],
            ["demand_records.demand_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("ai_demand_id"),
    )
    with op.batch_alter_table("topic_matrices", schema=None) as batch_op:
        batch_op.drop_index("ix_tm_panel_country")

    op.drop_table("topic_matrices")
    with op.batch_alter_table("discourse_flows", schema=None) as batch_op:
        batch_op.drop_index("ix_df_panel_id")
        batch_op.drop_index("ix_df_from_to")

    op.drop_table("discourse_flows")
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.drop_index("ix_cr_speaker_referenced")
        batch_op.drop_index("ix_cr_panel_id")

    op.drop_table("country_references")
    with op.batch_alter_table("bilateral_sentiments", schema=None) as batch_op:
        batch_op.drop_index("ix_bs_panel_pair")

    op.drop_table("bilateral_sentiments")
    with op.batch_alter_table("legacy_country_references", schema=None) as batch_op:
        batch_op.drop_index("idx_legacy_coref_to")
        batch_op.drop_index("idx_legacy_coref_from")

    op.drop_table("legacy_country_references")
    # ### end Alembic commands ###
