"""add_country_network_entities

Revision ID: 050ff3fd782c
Revises: 9652d437d1c3
Create Date: 2026-05-15 14:49:06.617407

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "050ff3fd782c"
down_revision: str | None = "9652d437d1c3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    # Create Enum types for PostgreSQL
    if conn.dialect.name == "postgresql":
        # Check and create demandcategory
        type_exists = conn.scalar(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'demandcategory')"
            )
        )
        if not type_exists:
            op.execute(
                "CREATE TYPE demandcategory AS ENUM ('INSTITUTIONAL_REFORM', 'SECURITY_ACTION', 'ECONOMIC_COOPERATION', 'HUMANITARIAN_RESPONSE', 'DIPLOMATIC_ENGAGEMENT', 'LEGAL_ACCOUNTABILITY')"
            )

        # Check and create risklevel
        type_exists = conn.scalar(
            sa.text("SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'risklevel')")
        )
        if not type_exists:
            op.execute(
                "CREATE TYPE risklevel AS ENUM ('NONE', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')"
            )

        # Check and create relationshiptype
        type_exists = conn.scalar(
            sa.text(
                "SELECT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'relationshiptype')"
            )
        )
        if not type_exists:
            op.execute(
                "CREATE TYPE relationshiptype AS ENUM ('ALLY', 'ADVERSARY', 'PARTNER', 'CAUTIOUS', 'NEUTRAL')"
            )

    # Drop views before altering tables to prevent SQLite view dependencies issues
    op.execute("DROP VIEW IF EXISTS v_f_fail_contextual_deep")
    op.execute("DROP VIEW IF EXISTS v_f_fail_ai_cross_reference")
    op.execute("DROP VIEW IF EXISTS v_f_fail_network_context")

    if "country_references" in tables:
        op.drop_table("country_references")

    op.create_table(
        "legacy_country_references",
        sa.Column("ref_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("sentiment_context", sa.Float(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("ref_id"),
    )
    with op.batch_alter_table("legacy_country_references", schema=None) as batch_op:
        batch_op.create_index("idx_legacy_coref_from", ["from_country"], unique=False)
        batch_op.create_index("idx_legacy_coref_to", ["to_country"], unique=False)

    op.create_table(
        "bilateral_sentiments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("from_country", sa.String(length=100), nullable=False),
        sa.Column("to_country", sa.String(length=100), nullable=False),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("interaction_count", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.String(length=20), nullable=False),
        sa.Column("affinity_score", sa.Float(), nullable=False),
        sa.Column("power_weighted_score", sa.Float(), nullable=False),
        sa.Column("diplomatic_distance", sa.Float(), nullable=False),
        sa.Column("last_updated", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("bilateral_sentiments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_bs_panel_pair", ["panel_id", "from_country", "to_country"], unique=True
        )

    op.create_table(
        "country_references",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("speaker_country", sa.String(length=100), nullable=False),
        sa.Column("referenced_country", sa.String(length=100), nullable=False),
        sa.Column("sentence_index", sa.Integer(), nullable=False),
        sa.Column("reference_context", sa.String(length=50), nullable=False),
        sa.Column("raw_sentiment_score", sa.Float(), nullable=False),
        sa.Column("speaker_power_level", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.create_index("ix_cr_panel_id", ["panel_id"], unique=False)
        batch_op.create_index(
            "ix_cr_speaker_referenced",
            ["speaker_country", "referenced_country"],
            unique=False,
        )

    op.create_table(
        "discourse_flows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("from_country", sa.String(length=100), nullable=False),
        sa.Column("to_country", sa.String(length=100), nullable=False),
        sa.Column("edge_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("sentiment_toward", sa.Float(), nullable=False),
        sa.Column("confrontational_count", sa.Integer(), nullable=False),
        sa.Column("cooperative_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discourse_flows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_df_from_to", ["from_country", "to_country"], unique=False
        )
        batch_op.create_index("ix_df_panel_id", ["panel_id"], unique=False)

    op.create_table(
        "topic_matrices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("topic_scores", sqlite.JSON(), nullable=False),
        sa.Column("dominant_topic", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_matrices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tm_panel_country", ["panel_id", "country"], unique=True
        )

    if "_alembic_tmp_ai_demand_analysis" in tables:
        op.drop_table("_alembic_tmp_ai_demand_analysis")
    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
            postgresql_using="demand_category::demandcategory",
        )

    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_insight", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_insight_version", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("insight_generated_at", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.add_column(sa.Column("backend", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("model_name", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_sentiment", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_emotion", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_risk_score", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("ai_risk_level", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_demand_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_topic", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_hedging_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_frame_type", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("ai_manipulation_score", sa.Float(), nullable=True)
        )
        batch_op.add_column(sa.Column("ai_politeness_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_evidence_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("logic_result", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("validation_flags", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("raw_response", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("tokens_used", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("latency_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("anomaly_types", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("anomaly_severity", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "risk_level",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"
            ),
            existing_nullable=True,
            postgresql_using="risk_level::risklevel",
        )
        batch_op.drop_index(batch_op.f("idx_ai_sent_prompt_ver"))

    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.alter_column(
            "relationship_type",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "ALLY",
                "ADVERSARY",
                "PARTNER",
                "CAUTIOUS",
                "NEUTRAL",
                name="relationshiptype",
            ),
            existing_nullable=True,
            postgresql_using="relationship_type::relationshiptype",
        )

    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
            postgresql_using="demand_category::demandcategory",
        )

    with op.batch_alter_table("panels", schema=None) as batch_op:
        batch_op.drop_column("replaced_by_panel_id")
        batch_op.drop_column("is_active")

    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_time", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("end_time", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duration", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_analyzed", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("logic_result", sa.Text(), nullable=True))
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
            postgresql_using="demand_category::demandcategory",
        )

    # Recreate views after altering tables
    op.execute("""
    CREATE VIEW v_f_fail_contextual_deep AS
    SELECT
        a.sent_id, a.panel_id, a.speaker_name, a.country, a.check_type,
        a.original_sentence, a.prev_sentence, a.next_sentence, a.triplet_text,
        a.contextual_factor AS AI_Baglamsal_Faktor, a.temporal_factor AS AI_Temporal_Faktor, 
        a.fail_reason AS AI_Neden_Fail,
        a.formula_gap AS AI_Formul_Eksigi, a.ai_misperception AS AI_AI_Yanilgisi, 
        a.correction_suggestion AS AI_Duzeltme_Onerisi,
        a.discrepancy_score, a.confidence_score AS AI_Guven_Skoru, a.processed_at,
        asa.sentiment_score AS AI_Duygu_Skoru, asa.risk_level AS AI_Risk_Skoru, 
        asa.manipulation_score AS AI_Manipulasyon_Skor
    FROM ai_fail_analysis a
    LEFT JOIN ai_sentence_analysis asa ON a.sent_id = asa.sent_id
    WHERE a.country NOT IN ('—','Unknown')
    """)

    op.execute("""
    CREATE VIEW v_f_fail_ai_cross_reference AS
    SELECT
        f.sent_id, f.check_type, f.fail_category AS AI_Fail_Kategorisi,
        f.formula_value, f.ai_value, f.discrepancy_score,
        asa.sentiment_score AS AI_Duygu_Skoru, asa.risk_level AS AI_Risk_Skoru, 
        asa.manipulation_score AS AI_Manipulasyon_Skor,
        f.fail_reason AS AI_Neden_Fail
    FROM ai_fail_analysis f
    LEFT JOIN ai_sentence_analysis asa ON f.sent_id = asa.sent_id
    WHERE f.country NOT IN ('—','Unknown')
    """)

    op.execute("""
    CREATE VIEW v_f_fail_network_context AS
    SELECT
        f.sent_id, f.speaker_name, f.country, f.check_type,
        dne.from_country, dne.to_country, dne.edge_type,
        cp.relationship_type, cp.affinity_score,
        f.fail_reason AS AI_Neden_Fail
    FROM ai_fail_analysis f
    LEFT JOIN sentences s ON f.sent_id = s.sent_id
    LEFT JOIN discourse_network_edges dne
        ON s.panel_id = dne.panel_id AND s.country = dne.from_country
    LEFT JOIN country_pair_sentiment cp
        ON dne.from_country = cp.from_country AND dne.to_country = cp.to_country
    WHERE f.country NOT IN ('—','Unknown')
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop views before altering tables in downgrade
    op.execute("DROP VIEW IF EXISTS v_f_fail_contextual_deep")
    op.execute("DROP VIEW IF EXISTS v_f_fail_ai_cross_reference")
    op.execute("DROP VIEW IF EXISTS v_f_fail_network_context")

    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("logic_result")
        batch_op.drop_column("ai_analyzed")
        batch_op.drop_column("duration")
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    with op.batch_alter_table("panels", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_active", sa.INTEGER(), server_default=sa.text("1"), nullable=True
            )
        )
        batch_op.add_column(sa.Column("replaced_by_panel_id", sa.TEXT(), nullable=True))

    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.alter_column(
            "relationship_type",
            existing_type=sa.Enum(
                "ALLY",
                "ADVERSARY",
                "PARTNER",
                "CAUTIOUS",
                "NEUTRAL",
                name="relationshiptype",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_ai_sent_prompt_ver"), ["prompt_version"], unique=False
        )
        batch_op.alter_column(
            "risk_level",
            existing_type=sa.Enum(
                "NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("anomaly_severity")
        batch_op.drop_column("anomaly_types")
        batch_op.drop_column("latency_ms")
        batch_op.drop_column("tokens_used")
        batch_op.drop_column("raw_response")
        batch_op.drop_column("validation_flags")
        batch_op.drop_column("logic_result")
        batch_op.drop_column("ai_evidence_type")
        batch_op.drop_column("ai_politeness_score")
        batch_op.drop_column("ai_manipulation_score")
        batch_op.drop_column("ai_frame_type")
        batch_op.drop_column("ai_hedging_score")
        batch_op.drop_column("ai_topic")
        batch_op.drop_column("ai_demand_type")
        batch_op.drop_column("ai_risk_level")
        batch_op.drop_column("ai_risk_score")
        batch_op.drop_column("ai_emotion")
        batch_op.drop_column("ai_sentiment")
        batch_op.drop_column("model_name")
        batch_op.drop_column("backend")

    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.drop_column("insight_generated_at")
        batch_op.drop_column("ai_insight_version")
        batch_op.drop_column("ai_insight")

    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("topic_matrices", schema=None) as batch_op:
        batch_op.drop_index("ix_tm_panel_country")

    op.drop_table("topic_matrices")
    with op.batch_alter_table("discourse_flows", schema=None) as batch_op:
        batch_op.drop_index("ix_df_panel_id")
        batch_op.drop_index("ix_df_from_to")

    op.drop_table("discourse_flows")
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.drop_index("ix_cr_speaker_referenced")
        batch_op.drop_index("ix_cr_panel_id")

    op.drop_table("country_references")
    with op.batch_alter_table("bilateral_sentiments", schema=None) as batch_op:
        batch_op.drop_index("ix_bs_panel_pair")

    op.drop_table("bilateral_sentiments")
    with op.batch_alter_table("legacy_country_references", schema=None) as batch_op:
        batch_op.drop_index("idx_legacy_coref_to")
        batch_op.drop_index("idx_legacy_coref_from")

    op.drop_table("legacy_country_references")

    # Recreate old country_references
    op.create_table(
        "country_references",
        sa.Column("ref_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("sentiment_context", sa.Float(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("ref_id"),
    )
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.create_index("idx_coref_from", ["from_country"], unique=False)
        batch_op.create_index("idx_coref_to", ["to_country"], unique=False)
    # Recreate views after altering tables in downgrade
    op.execute("""
    CREATE VIEW v_f_fail_contextual_deep AS
    SELECT
        a.sent_id, a.panel_id, a.speaker_name, a.country, a.check_type,
        a.original_sentence, a.prev_sentence, a.next_sentence, a.triplet_text,
        a.contextual_factor AS AI_Baglamsal_Faktor, a.temporal_factor AS AI_Temporal_Faktor, 
        a.fail_reason AS AI_Neden_Fail,
        a.formula_gap AS AI_Formul_Eksigi, a.ai_misperception AS AI_AI_Yanilgisi, 
        a.correction_suggestion AS AI_Duzeltme_Onerisi,
        a.discrepancy_score, a.confidence_score AS AI_Guven_Skoru, a.processed_at,
        asa.sentiment_score AS AI_Duygu_Skoru, asa.risk_level AS AI_Risk_Skoru, 
        asa.manipulation_score AS AI_Manipulasyon_Skor
    FROM ai_fail_analysis a
    LEFT JOIN ai_sentence_analysis asa ON a.sent_id = asa.sent_id
    WHERE a.country NOT IN ('—','Unknown')
    """)

    op.execute("""
    CREATE VIEW v_f_fail_ai_cross_reference AS
    SELECT
        f.sent_id, f.check_type, f.fail_category AS AI_Fail_Kategorisi,
        f.formula_value, f.ai_value, f.discrepancy_score,
        asa.sentiment_score AS AI_Duygu_Skoru, asa.risk_level AS AI_Risk_Skoru, 
        asa.manipulation_score AS AI_Manipulasyon_Skor,
        f.fail_reason AS AI_Neden_Fail
    FROM ai_fail_analysis f
    LEFT JOIN ai_sentence_analysis asa ON f.sent_id = asa.sent_id
    WHERE f.country NOT IN ('—','Unknown')
    """)

    op.execute("""
    CREATE VIEW v_f_fail_network_context AS
    SELECT
        f.sent_id, f.speaker_name, f.country, f.check_type,
        dne.from_country, dne.to_country, dne.edge_type,
        cp.relationship_type, cp.affinity_score,
        f.fail_reason AS AI_Neden_Fail
    FROM ai_fail_analysis f
    LEFT JOIN sentences s ON f.sent_id = s.sent_id
    LEFT JOIN discourse_network_edges dne
        ON s.panel_id = dne.panel_id AND s.country = dne.from_country
    LEFT JOIN country_pair_sentiment cp
        ON dne.from_country = cp.from_country AND dne.to_country = cp.to_country
    WHERE f.country NOT IN ('—','Unknown')
    """)
    # ### end Alembic commands ###
