"""add_speaker_id_to_country_references

Revision ID: 0b434cd674fe
Revises: hitl_formula_v2_001
Create Date: 2026-06-01 07:06:27.863277

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b434cd674fe"
down_revision: Union[str, None] = "hitl_formula_v2_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if is_sqlite:
        inspector = sa.inspect(bind)

        def drop_idx_if_exists(index_name, table_name):
            try:
                indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
                if index_name in indexes:
                    op.drop_index(index_name, table_name=table_name)
            except Exception:
                pass

        # Drop indexes directly
        drop_idx_if_exists("ix_actor_topic_documents_country", "actor_topic_documents")
        drop_idx_if_exists("ix_actor_topic_documents_file_id", "actor_topic_documents")
        drop_idx_if_exists("ix_proj_file_country", "actor_topic_projection")
        drop_idx_if_exists("ix_proj_topic_version", "actor_topic_projection")
        drop_idx_if_exists("ix_lineage_event", "aggregation_lineage")
        drop_idx_if_exists("ix_lineage_projection", "aggregation_lineage")
        drop_idx_if_exists("idx_review_file", "ai_human_review_queue")
        drop_idx_if_exists("idx_review_status", "ai_human_review_queue")
        drop_idx_if_exists("ix_events_file_country", "segment_events")
        drop_idx_if_exists("ix_events_pipeline_run", "segment_events")

        # Add column directly
        cols = [c["name"] for c in inspector.get_columns("country_references")]
        if "speaker_id" not in cols:
            op.add_column(
                "country_references",
                sa.Column("speaker_id", sa.String(length=255), nullable=True),
            )

        # Sentences index
        drop_idx_if_exists("idx_sent_code", "sentences")
        op.create_index("idx_sent_code", "sentences", ["sentence_code"], unique=True)
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table("actor_topic_documents", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_actor_topic_documents_country"))
            batch_op.drop_index(batch_op.f("ix_actor_topic_documents_file_id"))

        with op.batch_alter_table("actor_topic_projection", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_proj_file_country"))
            batch_op.drop_index(batch_op.f("ix_proj_topic_version"))

        with op.batch_alter_table("aggregation_lineage", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_lineage_event"))
            batch_op.drop_index(batch_op.f("ix_lineage_projection"))

        with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_comment="PromptRegistry versiyonu",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_fail_analysis", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_comment="PromptRegistry versiyonu",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_human_review_queue", schema=None) as batch_op:
            batch_op.alter_column(
                "status",
                existing_type=sa.VARCHAR(),
                server_default=None,
                nullable=False,
            )
            batch_op.drop_index(batch_op.f("idx_review_file"))
            batch_op.drop_index(batch_op.f("idx_review_status"))

        with op.batch_alter_table("ai_panel_synthesis", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_comment="PromptRegistry versiyonu",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_comment="PromptRegistry versiyonu",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
            batch_op.alter_column(
                "coherence_score",
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                comment="DualGate consensus coherence score (0.0-1.0)",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_consensus_level",
                existing_type=sa.VARCHAR(length=30),
                comment="CLEAN|SOFT_ANOMALY|HARD_ANOMALY|CRITICAL_ANOMALY",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_ai_decision",
                existing_type=sa.VARCHAR(length=20),
                comment="CONFIRMED|DISMISSED|ESCALATED|AI_ONLY|INCONCLUSIVE",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_ai_reasoning",
                existing_type=sa.VARCHAR(length=1000),
                comment="AI Anomaly Controller reasoning",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_detected_subtype",
                existing_type=sa.VARCHAR(length=50),
                comment="irony|rhetorical_strategy|coercive_signal|tone_drift",
                existing_nullable=True,
            )

        with op.batch_alter_table("country_references", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column("speaker_id", sa.String(length=255), nullable=True)
            )

        with op.batch_alter_table("formula_validation_audit", schema=None) as batch_op:
            batch_op.alter_column(
                "performed_at",
                existing_type=postgresql.TIMESTAMP(),
                server_default=None,
                existing_nullable=False,
            )

        with op.batch_alter_table("formula_validation_logs", schema=None) as batch_op:
            batch_op.alter_column(
                "log_version",
                existing_type=sa.INTEGER(),
                server_default=None,
                nullable=False,
            )
            batch_op.alter_column(
                "is_current",
                existing_type=sa.BOOLEAN(),
                server_default=None,
                nullable=False,
            )

        with op.batch_alter_table("reviewer_assignments", schema=None) as batch_op:
            batch_op.alter_column(
                "max_daily_reviews",
                existing_type=sa.INTEGER(),
                server_default=None,
                existing_nullable=False,
            )
            batch_op.alter_column(
                "current_daily_count",
                existing_type=sa.INTEGER(),
                server_default=None,
                existing_nullable=False,
            )
            batch_op.alter_column(
                "last_reset_at",
                existing_type=postgresql.TIMESTAMP(),
                server_default=None,
                existing_nullable=False,
            )
            batch_op.alter_column(
                "is_active",
                existing_type=sa.BOOLEAN(),
                server_default=None,
                existing_nullable=False,
            )
            batch_op.alter_column(
                "created_at",
                existing_type=postgresql.TIMESTAMP(),
                server_default=None,
                existing_nullable=False,
            )

        with op.batch_alter_table("segment_events", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_events_file_country"))
            batch_op.drop_index(batch_op.f("ix_events_pipeline_run"))

        with op.batch_alter_table("sentences", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("idx_sent_code"))
            batch_op.create_index("idx_sent_code", ["sentence_code"], unique=True)

        # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == "sqlite"

    if is_sqlite:
        inspector = sa.inspect(bind)

        def drop_idx_if_exists(index_name, table_name):
            try:
                indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
                if index_name in indexes:
                    op.drop_index(index_name, table_name=table_name)
            except Exception:
                pass

        def create_idx_if_not_exists(index_name, table_name, columns, unique=False):
            try:
                indexes = [idx["name"] for idx in inspector.get_indexes(table_name)]
                if index_name not in indexes:
                    op.create_index(index_name, table_name, columns, unique=unique)
            except Exception:
                pass

        drop_idx_if_exists("idx_sent_code", "sentences")
        create_idx_if_not_exists(
            "idx_sent_code", "sentences", ["sentence_code"], unique=False
        )

        create_idx_if_not_exists(
            "ix_events_pipeline_run",
            "segment_events",
            ["pipeline_run_id"],
            unique=False,
        )
        create_idx_if_not_exists(
            "ix_events_file_country",
            "segment_events",
            ["file_id", "country"],
            unique=False,
        )

        cols = [c["name"] for c in inspector.get_columns("country_references")]
        if "speaker_id" in cols:
            op.drop_column("country_references", "speaker_id")

        create_idx_if_not_exists(
            "ix_lineage_projection",
            "aggregation_lineage",
            ["projection_id"],
            unique=False,
        )
        create_idx_if_not_exists(
            "ix_lineage_event", "aggregation_lineage", ["event_id"], unique=False
        )

        create_idx_if_not_exists(
            "ix_proj_topic_version",
            "actor_topic_projection",
            ["topic", "topic_model_version"],
            unique=False,
        )
        create_idx_if_not_exists(
            "ix_proj_file_country",
            "actor_topic_projection",
            ["file_id", "country"],
            unique=False,
        )

        create_idx_if_not_exists(
            "ix_actor_topic_documents_file_id",
            "actor_topic_documents",
            ["file_id"],
            unique=False,
        )
        create_idx_if_not_exists(
            "ix_actor_topic_documents_country",
            "actor_topic_documents",
            ["country"],
            unique=False,
        )
    else:
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table("sentences", schema=None) as batch_op:
            batch_op.drop_index("idx_sent_code")
            batch_op.create_index(
                batch_op.f("idx_sent_code"), ["sentence_code"], unique=False
            )

        with op.batch_alter_table("segment_events", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_events_pipeline_run"), ["pipeline_run_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_events_file_country"),
                ["file_id", "country"],
                unique=False,
            )

        with op.batch_alter_table("reviewer_assignments", schema=None) as batch_op:
            batch_op.alter_column(
                "created_at",
                existing_type=postgresql.TIMESTAMP(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                existing_nullable=False,
            )
            batch_op.alter_column(
                "is_active",
                existing_type=sa.BOOLEAN(),
                server_default=sa.text("true"),
                existing_nullable=False,
            )
            batch_op.alter_column(
                "last_reset_at",
                existing_type=postgresql.TIMESTAMP(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                existing_nullable=False,
            )
            batch_op.alter_column(
                "current_daily_count",
                existing_type=sa.INTEGER(),
                server_default=sa.text("0"),
                existing_nullable=False,
            )
            batch_op.alter_column(
                "max_daily_reviews",
                existing_type=sa.INTEGER(),
                server_default=sa.text("50"),
                existing_nullable=False,
            )

        with op.batch_alter_table("formula_validation_logs", schema=None) as batch_op:
            batch_op.alter_column(
                "is_current",
                existing_type=sa.BOOLEAN(),
                server_default=sa.text("true"),
                nullable=True,
            )
            batch_op.alter_column(
                "log_version",
                existing_type=sa.INTEGER(),
                server_default=sa.text("1"),
                nullable=True,
            )

        with op.batch_alter_table("formula_validation_audit", schema=None) as batch_op:
            batch_op.alter_column(
                "performed_at",
                existing_type=postgresql.TIMESTAMP(),
                server_default=sa.text("CURRENT_TIMESTAMP"),
                existing_nullable=False,
            )

        with op.batch_alter_table("country_references", schema=None) as batch_op:
            batch_op.drop_column("speaker_id")

        with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
            batch_op.alter_column(
                "anomaly_detected_subtype",
                existing_type=sa.VARCHAR(length=50),
                comment=None,
                existing_comment="irony|rhetorical_strategy|coercive_signal|tone_drift",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_ai_reasoning",
                existing_type=sa.VARCHAR(length=1000),
                comment=None,
                existing_comment="AI Anomaly Controller reasoning",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_ai_decision",
                existing_type=sa.VARCHAR(length=20),
                comment=None,
                existing_comment="CONFIRMED|DISMISSED|ESCALATED|AI_ONLY|INCONCLUSIVE",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "anomaly_consensus_level",
                existing_type=sa.VARCHAR(length=30),
                comment=None,
                existing_comment="CLEAN|SOFT_ANOMALY|HARD_ANOMALY|CRITICAL_ANOMALY",
                existing_nullable=True,
            )
            batch_op.alter_column(
                "coherence_score",
                existing_type=sa.DOUBLE_PRECISION(precision=53),
                comment=None,
                existing_comment="DualGate consensus coherence score (0.0-1.0)",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu",
                existing_comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_panel_synthesis", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu",
                existing_comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_human_review_queue", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("idx_review_status"), ["status"], unique=False
            )
            batch_op.create_index(
                batch_op.f("idx_review_file"), ["file_id"], unique=False
            )
            batch_op.alter_column(
                "status",
                existing_type=sa.VARCHAR(),
                server_default=sa.text("'PENDING'::character varying"),
                nullable=True,
            )

        with op.batch_alter_table("ai_fail_analysis", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu",
                existing_comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_nullable=True,
            )

        with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
            batch_op.alter_column(
                "prompt_version",
                existing_type=sa.VARCHAR(length=80),
                comment="PromptRegistry versiyonu",
                existing_comment="PromptRegistry versiyonu — '{name}:{ver}:{hash}' formatı",
                existing_nullable=True,
            )

        with op.batch_alter_table("aggregation_lineage", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_lineage_projection"), ["projection_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_lineage_event"), ["event_id"], unique=False
            )

        with op.batch_alter_table("actor_topic_projection", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_proj_topic_version"),
                ["topic", "topic_model_version"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_proj_file_country"), ["file_id", "country"], unique=False
            )

        with op.batch_alter_table("actor_topic_documents", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_actor_topic_documents_file_id"),
                ["file_id"],
                unique=False,
            )
            batch_op.create_index(
                batch_op.f("ix_actor_topic_documents_country"),
                ["country"],
                unique=False,
            )

        # ### end Alembic commands ###end Alembic commands ###
