"""create_speakers_master_table

Revision ID: 1236a0b96382
Revises: 3e039beef918
Create Date: 2026-06-19 10:58:53.470275

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1236a0b96382"
down_revision: str | None = "3e039beef918"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dead_letter_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("original_event_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("event_version", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=False),
        sa.Column("moved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("dead_letter_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dead_letter_events_original_event_id"),
            ["original_event_id"],
            unique=False,
            if_not_exists=True,
        )

    op.create_table(
        "dki_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_id", sa.String(length=50), nullable=False),
        sa.Column("speaker_id", sa.String(length=50), nullable=False),
        sa.Column("session_id", sa.String(length=50), nullable=False),
        sa.Column("dki_score", sa.Float(), nullable=False),
        sa.Column("velocity", sa.Float(), nullable=False),
        sa.Column("semantic_shift", sa.Float(), nullable=False),
        sa.Column("debate_loading", sa.Float(), nullable=False),
        sa.Column("anomaly_flag", sa.Boolean(), nullable=False),
        sa.Column("calculation_method", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("dki_results", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_dki_results_analysis_id"),
            ["analysis_id"],
            unique=False,
            if_not_exists=True,
        )
        batch_op.create_index(
            batch_op.f("ix_dki_results_session_id"),
            ["session_id"],
            unique=False,
            if_not_exists=True,
        )
        batch_op.create_index(
            batch_op.f("ix_dki_results_speaker_id"),
            ["speaker_id"],
            unique=False,
            if_not_exists=True,
        )

    op.create_table(
        "speaker_positions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("speaker_id", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=True),
        sa.Column("wordfish_theta", sa.Float(), nullable=False),
        sa.Column("wordscores_t", sa.Float(), nullable=True),
        sa.Column("stance_density", sa.Float(), nullable=False),
        sa.Column("engagement_score", sa.Float(), nullable=False),
        sa.Column("sbi", sa.Float(), nullable=False),
        sa.Column("session_deviation", sa.Float(), nullable=True),
        sa.Column("alpha", sa.Float(), nullable=False),
        sa.Column("beta", sa.Float(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("gat_anomaly_score", sa.Float(), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("speaker_positions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sbi_session_speaker",
            ["session_id", "speaker_id"],
            unique=True,
            if_not_exists=True,
        )
        batch_op.create_index(
            batch_op.f("ix_speaker_positions_analysis_id"),
            ["analysis_id"],
            unique=False,
            if_not_exists=True,
        )
        batch_op.create_index(
            batch_op.f("ix_speaker_positions_sbi"),
            ["sbi"],
            unique=False,
            if_not_exists=True,
        )
        batch_op.create_index(
            batch_op.f("ix_speaker_positions_session_id"),
            ["session_id"],
            unique=False,
            if_not_exists=True,
        )
        batch_op.create_index(
            batch_op.f("ix_speaker_positions_speaker_id"),
            ["speaker_id"],
            unique=False,
            if_not_exists=True,
        )

    op.create_table(
        "speakers",
        sa.Column("speaker_id", sa.String(), nullable=False),
        sa.Column("canonical_name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("country_code", sa.String(length=3), nullable=True),
        sa.Column("country_name", sa.String(), nullable=True),
        sa.Column("bloc", sa.String(), nullable=True),
        sa.Column("power_level", sa.Float(), nullable=True),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("organization", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("appearance_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "data_source", sa.String(), server_default="pipeline_auto", nullable=False
        ),
        sa.Column("aliases", sa.JSON(), server_default="[]", nullable=True),
        sa.Column("metadata", sa.JSON(), server_default="{}", nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("speaker_id"),
        if_not_exists=True,
    )
    with op.batch_alter_table("speakers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_speakers_canonical_name"),
            ["canonical_name"],
            unique=True,
            if_not_exists=True,
        )

    with op.batch_alter_table("ai_human_review_queue", schema=None) as batch_op:
        batch_op.alter_column(
            "status", existing_type=sa.VARCHAR(), server_default=None, nullable=False
        )
        batch_op.alter_column(
            "flagged_at",
            existing_type=sa.TEXT(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=True,
        )

    with op.batch_alter_table("formula_validation_audit", schema=None) as batch_op:
        batch_op.alter_column(
            "performed_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("formula_validation_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "log_version",
            existing_type=sa.INTEGER(),
            server_default=None,
            nullable=False,
        )
        batch_op.alter_column(
            "is_current",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            nullable=False,
        )

    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("processed", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("attempts", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.add_column(
            sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True)
        )
        batch_op.alter_column(
            "event_version",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("ix_outbox_events_status"))
        batch_op.create_index(
            batch_op.f("ix_outbox_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_outbox_events_processed"), ["processed"], unique=False
        )
        batch_op.drop_column("retry_count")
        batch_op.drop_column("status")
        batch_op.drop_column("processed_at")
        batch_op.drop_column("aggregate_type")

    with op.batch_alter_table("pattern_records", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=False,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "model_name",
            existing_type=sa.VARCHAR(length=100),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "language",
            existing_type=sa.VARCHAR(length=10),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("idx_prompt_versions_prompt_id"))
        batch_op.drop_index(batch_op.f("idx_prompt_versions_template_hash"))
        batch_op.create_index(
            batch_op.f("ix_prompt_versions_prompt_id"), ["prompt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_prompt_versions_template_hash"),
            ["template_hash"],
            unique=False,
        )

    with op.batch_alter_table("reviewer_assignments", schema=None) as batch_op:
        batch_op.alter_column(
            "max_daily_reviews",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "current_daily_count",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "last_reset_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("segments", schema=None) as batch_op:
        # Drop old FK to speaker_profiles (if exists), skip adding new FK to speakers
        # (segments already has data with speaker_ids not yet in speakers table)
        try:
            batch_op.drop_constraint(
                "fk_segments_speaker_id_speaker_profiles", type_="foreignkey"
            )
        except Exception:
            pass  # Constraint may not exist

    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.alter_column(
            "speaker_id",
            existing_type=sa.TEXT(),
            type_=sa.String(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "embedding",
            existing_type=sa.NUMERIC(precision=384),
            type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
            existing_nullable=True,
        )
        # Skip FK to speakers — data backfill needed first

    # Skip FK on speaker_profiles — speakers table needs backfill first
    # with op.batch_alter_table('speaker_profiles', schema=None) as batch_op:
    #     batch_op.create_foreign_key('fk_speaker_profiles_speaker_id_speakers', 'speakers', ['speaker_id'], ['speaker_id'])

    with op.batch_alter_table("webhook_subscriptions", schema=None) as batch_op:
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=None,
            existing_nullable=False,
        )

    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.alter_column(
            "is_negated",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_hedge",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_diplomatic_term",
            existing_type=sa.BOOLEAN(),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.alter_column(
            "is_diplomatic_term",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_hedge",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_negated",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("(false)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("webhook_subscriptions", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("speaker_profiles", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_speaker_profiles_speaker_id_speakers", type_="foreignkey"
        )

    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.drop_constraint("fk_sentences_speaker_id_speakers", type_="foreignkey")
        batch_op.alter_column(
            "embedding",
            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
            type_=sa.NUMERIC(precision=384),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "speaker_id",
            existing_type=sa.String(),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.drop_constraint("fk_segments_speaker_id_speakers", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_segments_speaker_id_speaker_profiles",
            "speaker_profiles",
            ["speaker_id"],
            ["speaker_id"],
        )

    with op.batch_alter_table("reviewer_assignments", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("1"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "last_reset_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "current_daily_count",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "max_daily_reviews",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'50'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("prompt_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompt_versions_template_hash"))
        batch_op.drop_index(batch_op.f("ix_prompt_versions_prompt_id"))
        batch_op.create_index(
            batch_op.f("idx_prompt_versions_template_hash"),
            ["template_hash"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_prompt_versions_prompt_id"), ["prompt_id"], unique=False
        )
        batch_op.alter_column(
            "language",
            existing_type=sa.VARCHAR(length=10),
            server_default=sa.text("'any'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "model_name",
            existing_type=sa.VARCHAR(length=100),
            server_default=sa.text("'gpt-4o'"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "is_active",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("'true'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("pattern_records", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            nullable=True,
            existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
        )

    with op.batch_alter_table("outbox_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("aggregate_type", sa.VARCHAR(length=100), nullable=False)
        )
        batch_op.add_column(sa.Column("processed_at", sa.DATETIME(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "status",
                sa.VARCHAR(length=20),
                server_default=sa.text("'pending'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "retry_count",
                sa.INTEGER(),
                server_default=sa.text("'0'"),
                nullable=False,
            )
        )
        batch_op.drop_index(batch_op.f("ix_outbox_events_processed"))
        batch_op.drop_index(batch_op.f("ix_outbox_events_event_type"))
        batch_op.create_index(
            batch_op.f("ix_outbox_events_status"), ["status"], unique=False
        )
        batch_op.alter_column(
            "created_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "event_version",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            existing_nullable=False,
        )
        batch_op.drop_column("next_attempt_at")
        batch_op.drop_column("last_attempt_at")
        batch_op.drop_column("attempts")
        batch_op.drop_column("processed")

    with op.batch_alter_table("formula_validation_logs", schema=None) as batch_op:
        batch_op.alter_column(
            "is_current",
            existing_type=sa.BOOLEAN(),
            server_default=sa.text("1"),
            nullable=True,
        )
        batch_op.alter_column(
            "log_version",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'1'"),
            nullable=True,
        )

    with op.batch_alter_table("formula_validation_audit", schema=None) as batch_op:
        batch_op.alter_column(
            "performed_at",
            existing_type=sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            existing_nullable=False,
        )

    with op.batch_alter_table("ai_human_review_queue", schema=None) as batch_op:
        batch_op.alter_column(
            "flagged_at",
            existing_type=sa.TEXT(),
            server_default=sa.text("(datetime('now'))"),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "status",
            existing_type=sa.VARCHAR(),
            server_default=sa.text("'PENDING'"),
            nullable=True,
        )

    with op.batch_alter_table("speakers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_speakers_canonical_name"))

    op.drop_table("speakers")
    with op.batch_alter_table("speaker_positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_speaker_positions_speaker_id"))
        batch_op.drop_index(batch_op.f("ix_speaker_positions_session_id"))
        batch_op.drop_index(batch_op.f("ix_speaker_positions_sbi"))
        batch_op.drop_index(batch_op.f("ix_speaker_positions_analysis_id"))
        batch_op.drop_index("ix_sbi_session_speaker")

    op.drop_table("speaker_positions")
    with op.batch_alter_table("dki_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dki_results_speaker_id"))
        batch_op.drop_index(batch_op.f("ix_dki_results_session_id"))
        batch_op.drop_index(batch_op.f("ix_dki_results_analysis_id"))

    op.drop_table("dki_results")
    with op.batch_alter_table("dead_letter_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dead_letter_events_original_event_id"))

    op.drop_table("dead_letter_events")
    # ### end Alembic commands ###
