"""add_audit_log_table

Revision ID: 20260624_add_audit_log
Revises: 20260623_add_provenance
Create Date: 2026-06-24 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260624_add_audit_log"
down_revision: str | None = "20260623_add_provenance"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("actor_id", sa.String(255), nullable=False),
        sa.Column("action", sa.String(100), nullable=False),
        sa.Column("resource_type", sa.String(100), nullable=False),
        sa.Column("resource_id", sa.String(255), nullable=False),
        sa.Column("before_state", sa.JSON(), nullable=True),
        sa.Column("after_state", sa.JSON(), nullable=True),
        sa.Column("correlation_id", sa.String(255), nullable=True),
        sa.Column("ip_address", sa.String(45), nullable=True),
        sa.Column("user_agent", sa.String(500), nullable=True),
        sa.Column("hash_chain", sa.String(64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Single column indexes
    op.create_index(
        op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_log_resource_type"), "audit_log", ["resource_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_resource_id"), "audit_log", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_correlation_id"),
        "audit_log",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_log_hash_chain"), "audit_log", ["hash_chain"], unique=False
    )

    # Composite indexes for common query patterns
    op.create_index(
        op.f("ix_audit_log_resource"),
        "audit_log",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_log_actor_action"),
        "audit_log",
        ["actor_id", "action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_log_timestamp_action"),
        "audit_log",
        ["timestamp", "action"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite indexes
    op.drop_index(op.f("ix_audit_log_timestamp_action"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_action"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_resource"), table_name="audit_log")

    # Drop single column indexes
    op.drop_index(op.f("ix_audit_log_hash_chain"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_correlation_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_resource_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_resource_type"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")

    op.drop_table("audit_log")
    # ### end Alembic commands ###
