"""Add quality assurance tables

Revision ID: 20260512_add_quality_assurance_tables
Revises:
Create Date: 2026-05-12 13:33:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260512_add_quality_assurance_tables"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create processed_files table
    op.create_table(
        "processed_files",
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("parser_version", sa.Text(), nullable=True),
        sa.Column("speaker_map_version", sa.Text(), nullable=True),
        sa.Column(
            "first_processed_at",
            sa.Text(),
            server_default=sa.text("datetime('now')"),
            nullable=True,
        ),
        sa.Column("last_processed_at", sa.Text(), nullable=True),
        sa.Column("reprocess_count", sa.Integer(), nullable=False),
        sa.Column("force_rebuild", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("file_hash"),
        sa.UniqueConstraint("idempotency_key"),
    )

    # Create ai_human_review_queue table
    op.create_table(
        "ai_human_review_queue",
        sa.Column("review_id", sa.Integer(), nullable=False),
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.Column("seg_id", sa.Text(), nullable=True),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("trigger_type", sa.String(), nullable=False),
        sa.Column("ai_risk_score", sa.Integer(), nullable=True),
        sa.Column("anomaly_types", sa.Text(), nullable=True),
        sa.Column("uncertainty_score", sa.Integer(), nullable=True),
        sa.Column(
            "status", sa.String(), server_default=sa.text("PENDING"), nullable=True
        ),
        sa.Column("assigned_to", sa.Text(), nullable=True),
        sa.Column("reviewer_notes", sa.Text(), nullable=True),
        sa.Column("original_ai_json", sa.Text(), nullable=False),
        sa.Column("corrected_json", sa.Text(), nullable=True),
        sa.Column(
            "flagged_at",
            sa.Text(),
            server_default=sa.text("datetime('now')"),
            nullable=True,
        ),
        sa.Column("reviewed_at", sa.Text(), nullable=True),
        sa.Column("review_duration_sec", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("review_id"),
    )
    op.create_index("idx_review_status", "ai_human_review_queue", ["status"])
    op.create_index("idx_review_panel", "ai_human_review_queue", ["panel_id"])

    # Create drift_events table
    op.create_table(
        "drift_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("speaker_id", sa.String(), nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("drift_type", sa.String(), nullable=False),
        sa.Column("start_position", sa.Integer(), nullable=False),
        sa.Column("end_position", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("before_state", sa.Text(), nullable=True),
        sa.Column("after_state", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    # Add soft delete columns to panels table
    op.add_column(
        "panels",
        sa.Column(
            "is_active", sa.Integer(), server_default=sa.text("1"), nullable=True
        ),
    )
    op.add_column("panels", sa.Column("replaced_by_panel_id", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Remove soft delete columns from panels table
    op.drop_column("panels", "replaced_by_panel_id")
    op.drop_column("panels", "is_active")

    # Drop drift_events table
    op.drop_table("drift_events")

    # Drop indexes and ai_human_review_queue table
    op.drop_index("idx_review_panel", table_name="ai_human_review_queue")
    op.drop_index("idx_review_status", table_name="ai_human_review_queue")
    op.drop_table("ai_human_review_queue")

    # Drop processed_files table
    op.drop_table("processed_files")

    # ### end Alembic commands ###
