"""add_correction_events_table

Revision ID: 20260625_add_correction_events
Revises: 20260624_add_audit_log
Create Date: 2026-06-25 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260625_add_correction_events"
down_revision: str | None = "20260624_add_audit_log"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "correction_events",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("sentence_id", sa.String(255), nullable=False),
        sa.Column("field_corrected", sa.String(100), nullable=False),
        sa.Column("original_value", sa.JSON(), nullable=True),
        sa.Column("corrected_value", sa.JSON(), nullable=False),
        sa.Column("prompt_version", sa.String(50), nullable=False),
        sa.Column("ai_confidence", sa.Float(), nullable=False),
        sa.Column("corrector_id", sa.String(255), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("context_snapshot", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    # Single column indexes
    op.create_index(
        op.f("ix_correction_events_sentence_id"),
        "correction_events",
        ["sentence_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_events_field_corrected"),
        "correction_events",
        ["field_corrected"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_events_prompt_version"),
        "correction_events",
        ["prompt_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_events_corrector_id"),
        "correction_events",
        ["corrector_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_events_timestamp"),
        "correction_events",
        ["timestamp"],
        unique=False,
    )

    # Composite indexes for common query patterns
    op.create_index(
        op.f("ix_correction_events_field_prompt"),
        "correction_events",
        ["field_corrected", "prompt_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_events_timestamp_field"),
        "correction_events",
        ["timestamp", "field_corrected"],
        unique=False,
    )
    op.create_index(
        op.f("ix_correction_events_corrector_timestamp"),
        "correction_events",
        ["corrector_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite indexes
    op.drop_index(
        op.f("ix_correction_events_corrector_timestamp"),
        table_name="correction_events",
    )
    op.drop_index(
        op.f("ix_correction_events_timestamp_field"),
        table_name="correction_events",
    )
    op.drop_index(
        op.f("ix_correction_events_field_prompt"),
        table_name="correction_events",
    )

    # Drop single column indexes
    op.drop_index(
        op.f("ix_correction_events_timestamp"),
        table_name="correction_events",
    )
    op.drop_index(
        op.f("ix_correction_events_corrector_id"),
        table_name="correction_events",
    )
    op.drop_index(
        op.f("ix_correction_events_prompt_version"),
        table_name="correction_events",
    )
    op.drop_index(
        op.f("ix_correction_events_field_corrected"),
        table_name="correction_events",
    )
    op.drop_index(
        op.f("ix_correction_events_sentence_id"),
        table_name="correction_events",
    )

    op.drop_table("correction_events")
    # ### end Alembic commands ###
