"""add_weight_calibration_tables

Revision ID: 20260625_add_weight_calibration
Revises: 20260625_add_correction_events
Create Date: 2026-06-25 00:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260625_add_weight_calibration"
down_revision: str | None = "20260625_add_correction_events"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calibratable_parameters",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("parameter_type", sa.String(50), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("min_value", sa.Float(), nullable=False),
        sa.Column("max_value", sa.Float(), nullable=False),
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    op.create_index(
        op.f("ix_calibratable_parameters_parameter_type"),
        "calibratable_parameters",
        ["parameter_type"],
        unique=False,
    )

    op.create_table(
        "weight_update_proposals",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("parameter_id", sa.String(36), nullable=False),
        sa.Column("parameter_name", sa.String(255), nullable=False),
        sa.Column("old_value", sa.Float(), nullable=False),
        sa.Column("proposed_value", sa.Float(), nullable=False),
        sa.Column("correction_signal", sa.Float(), nullable=False),
        sa.Column("learning_rate", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(1000), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(50), nullable=False),
        sa.Column("approved_by", sa.String(255), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rollback_version", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_weight_update_proposals_parameter_id"),
        "weight_update_proposals",
        ["parameter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_update_proposals_created_at"),
        "weight_update_proposals",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_update_proposals_status"),
        "weight_update_proposals",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_update_proposals_parameter_status"),
        "weight_update_proposals",
        ["parameter_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_update_proposals_created_status"),
        "weight_update_proposals",
        ["created_at", "status"],
        unique=False,
    )

    op.create_table(
        "weight_version_history",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("parameter_id", sa.String(36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_by", sa.String(255), nullable=False),
        sa.Column("reason", sa.String(1000), nullable=False),
        sa.Column("proposal_id", sa.String(36), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        op.f("ix_weight_version_history_parameter_id"),
        "weight_version_history",
        ["parameter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_version_history_version"),
        "weight_version_history",
        ["version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_version_history_parameter_version"),
        "weight_version_history",
        ["parameter_id", "version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_weight_version_history_proposal_id"),
        "weight_version_history",
        ["proposal_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_weight_version_history_proposal_id"),
        table_name="weight_version_history",
    )
    op.drop_index(
        op.f("ix_weight_version_history_parameter_version"),
        table_name="weight_version_history",
    )
    op.drop_index(
        op.f("ix_weight_version_history_version"),
        table_name="weight_version_history",
    )
    op.drop_index(
        op.f("ix_weight_version_history_parameter_id"),
        table_name="weight_version_history",
    )

    op.drop_table("weight_version_history")

    op.drop_index(
        op.f("ix_weight_update_proposals_created_status"),
        table_name="weight_update_proposals",
    )
    op.drop_index(
        op.f("ix_weight_update_proposals_parameter_status"),
        table_name="weight_update_proposals",
    )
    op.drop_index(
        op.f("ix_weight_update_proposals_status"),
        table_name="weight_update_proposals",
    )
    op.drop_index(
        op.f("ix_weight_update_proposals_created_at"),
        table_name="weight_update_proposals",
    )
    op.drop_index(
        op.f("ix_weight_update_proposals_parameter_id"),
        table_name="weight_update_proposals",
    )

    op.drop_table("weight_update_proposals")

    op.drop_index(
        op.f("ix_calibratable_parameters_parameter_type"),
        table_name="calibratable_parameters",
    )

    op.drop_table("calibratable_parameters")
    # ### end Alembic commands ###
