"""add_provenance_graphs_table

Revision ID: 20260623_add_provenance
Revises: 9042307bdc61
Create Date: 2026-06-23 21:18:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260623_add_provenance"
down_revision: str | None = "9042307bdc61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provenance_graphs",
        sa.Column("id", sa.String(36), nullable=False),
        sa.Column("result_id", sa.String(255), nullable=False),
        sa.Column("correlation_id", sa.String(255), nullable=True),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("edges", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("version", sa.String(50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provenance_graphs_result_id"),
        "provenance_graphs",
        ["result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provenance_graphs_correlation_id"),
        "provenance_graphs",
        ["correlation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_provenance_graphs_correlation_id"), table_name="provenance_graphs"
    )
    op.drop_index(
        op.f("ix_provenance_graphs_result_id"), table_name="provenance_graphs"
    )
    op.drop_table("provenance_graphs")
    # ### end Alembic commands ###
