"""initial_schema

Revision ID: 378a5aaa5bbd
Revises:
Create Date: 2026-05-10 02:28:16.107564

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "378a5aaa5bbd"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_cache",
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("hash"),
    )
    with op.batch_alter_table("ai_cache", schema=None) as batch_op:
        batch_op.create_index("idx_cache_hash", ["hash"], unique=False)

    op.create_table(
        "ai_contextual_flags",
        sa.Column("flag_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.Text(), nullable=False),
        sa.Column("seg_id", sa.Text(), nullable=True),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("anomaly_type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("flag_category", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("ai_values", sa.Text(), nullable=True),
        sa.Column("formula_values", sa.Text(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("flag_id"),
    )
    with op.batch_alter_table("ai_contextual_flags", schema=None) as batch_op:
        batch_op.create_index("idx_flags_cat", ["flag_category"], unique=False)
        batch_op.create_index("idx_flags_country", ["country"], unique=False)
        batch_op.create_index("idx_flags_sent", ["sent_id"], unique=False)
        batch_op.create_index("idx_flags_sev", ["severity"], unique=False)
        batch_op.create_index("idx_flags_type", ["anomaly_type"], unique=False)

    op.create_table(
        "ai_fail_analysis",
        sa.Column("fail_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.Text(), nullable=False),
        sa.Column("seg_id", sa.Text(), nullable=True),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("global_sent_order", sa.Integer(), nullable=True),
        sa.Column("check_type", sa.Text(), nullable=False),
        sa.Column("formula_value", sa.Text(), nullable=True),
        sa.Column("ai_value", sa.Text(), nullable=True),
        sa.Column("discrepancy_score", sa.Float(), nullable=True),
        sa.Column("original_sentence", sa.Text(), nullable=True),
        sa.Column("triplet_text", sa.Text(), nullable=True),
        sa.Column("prev_sentence", sa.Text(), nullable=True),
        sa.Column("next_sentence", sa.Text(), nullable=True),
        sa.Column("prev_sent_id", sa.Text(), nullable=True),
        sa.Column("next_sent_id", sa.Text(), nullable=True),
        sa.Column("kgi_score", sa.Float(), nullable=False),
        sa.Column("risk_delta", sa.Float(), nullable=False),
        sa.Column("emotion_shift", sa.Float(), nullable=False),
        sa.Column("topic_shift", sa.Float(), nullable=False),
        sa.Column("formula_inconsistency_score", sa.Float(), nullable=False),
        sa.Column("ai_manipulation_score", sa.Float(), nullable=False),
        sa.Column("ai_hedging_score", sa.Float(), nullable=False),
        sa.Column("ai_risk_score", sa.Float(), nullable=False),
        sa.Column("ai_sentiment_score", sa.Float(), nullable=False),
        sa.Column("ai_tone", sa.Text(), nullable=True),
        sa.Column("ai_frame", sa.Text(), nullable=True),
        sa.Column("anomaly_types", sa.Text(), nullable=True),
        sa.Column("anomaly_count", sa.Integer(), nullable=False),
        sa.Column("fail_reason", sa.Text(), nullable=True),
        sa.Column("negation_type", sa.Text(), nullable=True),
        sa.Column("negation_scope", sa.Text(), nullable=True),
        sa.Column("contextual_factor", sa.Text(), nullable=True),
        sa.Column("temporal_factor", sa.Text(), nullable=True),
        sa.Column("formula_gap", sa.Text(), nullable=True),
        sa.Column("ai_misperception", sa.Text(), nullable=True),
        sa.Column("correction_suggestion", sa.Text(), nullable=True),
        sa.Column("comparative_correction", sa.Text(), nullable=True),
        sa.Column("fail_category", sa.Text(), nullable=True),
        sa.Column("anomaly_link", sa.Text(), nullable=True),
        sa.Column("linguistic_marker", sa.Text(), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("from_cache", sa.Boolean(), nullable=False),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("fail_id"),
    )
    with op.batch_alter_table("ai_fail_analysis", schema=None) as batch_op:
        batch_op.create_index("idx_fail_check", ["check_type"], unique=False)
        batch_op.create_index("idx_fail_country", ["country"], unique=False)
        batch_op.create_index("idx_fail_kategori", ["fail_category"], unique=False)
        batch_op.create_index("idx_fail_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_fail_sent", ["sent_id"], unique=False)

    op.create_table(
        "ai_fail_cache",
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("result_json", sa.Text(), nullable=False),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("hash"),
    )
    with op.batch_alter_table("ai_fail_cache", schema=None) as batch_op:
        batch_op.create_index("idx_fcache_hash", ["hash"], unique=False)

    op.create_table(
        "ai_fail_patterns",
        sa.Column("pattern_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fail_category", sa.Text(), nullable=False),
        sa.Column("negation_type", sa.Text(), nullable=True),
        sa.Column("check_type", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("power_level_avg", sa.Float(), nullable=False),
        sa.Column("avg_discrepancy", sa.Float(), nullable=False),
        sa.Column("avg_ai_confidence", sa.Float(), nullable=False),
        sa.Column("dominant_negation_type", sa.Text(), nullable=True),
        sa.Column("affected_panels", sa.Text(), nullable=True),
        sa.Column("example_sent_id", sa.Text(), nullable=True),
        sa.Column("example_sentence", sa.Text(), nullable=True),
        sa.Column("example_explanation", sa.Text(), nullable=True),
        sa.Column("recurrence_count", sa.Integer(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("pattern_id"),
    )
    with op.batch_alter_table("ai_fail_patterns", schema=None) as batch_op:
        batch_op.create_index("idx_fail_pattern_chk", ["check_type"], unique=False)
        batch_op.create_index("idx_fail_pattern_kat", ["fail_category"], unique=False)

    op.create_table(
        "ai_validation_log",
        sa.Column("val_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.Text(), nullable=False),
        sa.Column("seg_id", sa.Text(), nullable=True),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("check_type", sa.Text(), nullable=False),
        sa.Column("formula_value", sa.Text(), nullable=True),
        sa.Column("ai_value", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("discrepancy_score", sa.Float(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("context_note", sa.Text(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("val_id"),
    )
    with op.batch_alter_table("ai_validation_log", schema=None) as batch_op:
        batch_op.create_index("idx_val_result", ["result"], unique=False)
        batch_op.create_index("idx_val_sent", ["sent_id"], unique=False)
        batch_op.create_index("idx_val_type", ["check_type"], unique=False)

    op.create_table(
        "country_pair_sentiment",
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("total_mentions", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=True),
        sa.Column("interaction_count", sa.Integer(), nullable=False),
        sa.Column("relationship_type", sa.Text(), nullable=True),
        sa.Column("affinity_score", sa.Float(), nullable=True),
        sa.Column("power_weighted_score", sa.Float(), nullable=False),
        sa.Column("diplomatic_distance", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("from_country", "to_country"),
    )
    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.create_index("idx_pair_from", ["from_country"], unique=False)

    op.create_table(
        "panels",
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("panel_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("inferred_theme", sa.Text(), nullable=True),
        sa.Column("date_str", sa.Text(), nullable=True),
        sa.Column("file_format", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=True),
        sa.Column("n_segments", sa.Integer(), nullable=False),
        sa.Column("n_sentences", sa.Integer(), nullable=False),
        sa.Column("n_speakers", sa.Integer(), nullable=False),
        sa.Column("n_countries", sa.Integer(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("total_duration_sec", sa.Integer(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("panel_id"),
        sa.UniqueConstraint("file_hash"),
    )
    op.create_table(
        "speakers",
        sa.Column("speaker_id", sa.String(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("bloc", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("influence_tier", sa.Text(), nullable=True),
        sa.Column("first_seen_panel", sa.Text(), nullable=True),
        sa.Column("n_panels", sa.Integer(), nullable=False),
        sa.Column("n_segments", sa.Integer(), nullable=False),
        sa.Column("n_sentences", sa.Integer(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("total_duration_sec", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("dominant_emotion", sa.Text(), nullable=True),
        sa.Column("dominant_topic", sa.Text(), nullable=True),
        sa.Column("cooperative_pct", sa.Float(), nullable=False),
        sa.Column("confrontational_pct", sa.Float(), nullable=False),
        sa.Column("risk_event_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("speaker_id"),
    )
    op.create_table(
        "ai_fail_anomaly_cross",
        sa.Column("cross_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.Text(), nullable=False),
        sa.Column("fail_id", sa.Integer(), nullable=True),
        sa.Column("anomaly_type", sa.Text(), nullable=False),
        sa.Column("severity", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "detected_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["fail_id"],
            ["ai_fail_analysis.fail_id"],
        ),
        sa.PrimaryKeyConstraint("cross_id"),
    )
    with op.batch_alter_table("ai_fail_anomaly_cross", schema=None) as batch_op:
        batch_op.create_index("idx_fac_fail", ["fail_id"], unique=False)
        batch_op.create_index("idx_fac_sent", ["sent_id"], unique=False)

    op.create_table(
        "ai_panel_synthesis",
        sa.Column("synthesis_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("panel_summary", sa.Text(), nullable=True),
        sa.Column("power_balance", sa.Text(), nullable=True),
        sa.Column("critical_moments", sa.Text(), nullable=True),
        sa.Column("outlook", sa.Text(), nullable=True),
        sa.Column("risk_map", sa.Text(), nullable=True),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.PrimaryKeyConstraint("synthesis_id"),
        sa.UniqueConstraint("panel_id"),
    )
    op.create_table(
        "country_stats",
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("n_segments", sa.Integer(), nullable=False),
        sa.Column("n_sentences", sa.Integer(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("total_duration_sec", sa.Integer(), nullable=False),
        sa.Column("words_per_minute", sa.Float(), nullable=True),
        sa.Column("avg_sentiment", sa.Float(), nullable=True),
        sa.Column("dominant_emotion", sa.Text(), nullable=True),
        sa.Column("dominant_topic", sa.Text(), nullable=True),
        sa.Column("topic_scores", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.PrimaryKeyConstraint("country", "panel_id"),
    )
    op.create_table(
        "discourse_network_edges",
        sa.Column("edge_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("edge_type", sa.Text(), nullable=True),
        sa.Column("power_source", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.PrimaryKeyConstraint("edge_id"),
    )
    with op.batch_alter_table("discourse_network_edges", schema=None) as batch_op:
        batch_op.create_index("idx_net_from", ["from_country"], unique=False)

    op.create_table(
        "segments",
        sa.Column("seg_id", sa.String(), nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("speaker_id", sa.String(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("bloc", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("seq_order", sa.Integer(), nullable=True),
        sa.Column("global_sent_start", sa.Integer(), nullable=False),
        sa.Column("ts_start", sa.Text(), nullable=True),
        sa.Column("ts_end", sa.Text(), nullable=True),
        sa.Column("ts_start_sec", sa.Integer(), nullable=False),
        sa.Column("ts_end_sec", sa.Integer(), nullable=False),
        sa.Column("duration_sec", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("sentence_count", sa.Integer(), nullable=False),
        sa.Column("avg_word_len", sa.Float(), nullable=True),
        sa.Column("vader_pos", sa.Float(), nullable=True),
        sa.Column("vader_neg", sa.Float(), nullable=True),
        sa.Column("vader_neu", sa.Float(), nullable=True),
        sa.Column("vader_compound", sa.Float(), nullable=True),
        sa.Column("diplo_compound", sa.Float(), nullable=True),
        sa.Column("emotion_category", sa.Text(), nullable=True),
        sa.Column("key_phrases", sa.Text(), nullable=True),
        sa.Column("tfidf_keywords", sa.Text(), nullable=True),
        sa.Column("topic_scores", sa.JSON(), nullable=True),
        sa.Column("dominant_topic", sa.Text(), nullable=True),
        sa.Column("entities_gpe", sa.JSON(), nullable=True),
        sa.Column("entities_org", sa.JSON(), nullable=True),
        sa.Column("entities_person", sa.JSON(), nullable=True),
        sa.Column("risk_signals", sa.JSON(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("demand_count", sa.Integer(), nullable=False),
        sa.Column("rhetoric_patterns", sa.JSON(), nullable=True),
        sa.Column("risk_trend", sa.Text(), nullable=True),
        sa.Column("risk_trajectory", sa.Text(), nullable=True),
        sa.Column("intro_sentiment", sa.Float(), nullable=False),
        sa.Column("develop_sentiment", sa.Float(), nullable=False),
        sa.Column("concl_sentiment", sa.Float(), nullable=False),
        sa.Column("demand_concentration", sa.JSON(), nullable=True),
        sa.Column("sbi_score", sa.Float(), nullable=False),
        sa.Column("dki_score", sa.Float(), nullable=False),
        sa.Column("formula_manip_score", sa.Float(), nullable=False),
        sa.Column("inconsistency_score", sa.Float(), nullable=False),
        sa.Column("avg_hedging_score", sa.Float(), nullable=False),
        sa.Column("avg_politeness_ratio", sa.Float(), nullable=False),
        sa.Column("dominant_frame", sa.Text(), nullable=True),
        sa.Column("dominant_audience", sa.Text(), nullable=True),
        sa.Column("dominant_evidence", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.speaker_id"],
        ),
        sa.PrimaryKeyConstraint("seg_id"),
    )
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.create_index("idx_seg_country", ["country"], unique=False)
        batch_op.create_index("idx_seg_emotion", ["emotion_category"], unique=False)
        batch_op.create_index("idx_seg_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_seg_topic", ["dominant_topic"], unique=False)

    op.create_table(
        "speaker_profiles",
        sa.Column("speaker_id", sa.String(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("bloc", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("influence_tier", sa.Text(), nullable=True),
        sa.Column("n_panels", sa.Integer(), nullable=False),
        sa.Column("n_segments", sa.Integer(), nullable=False),
        sa.Column("n_sentences", sa.Integer(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("dominant_emotion", sa.Text(), nullable=True),
        sa.Column("dominant_topic", sa.Text(), nullable=True),
        sa.Column("cooperative_pct", sa.Float(), nullable=False),
        sa.Column("constructive_pct", sa.Float(), nullable=False),
        sa.Column("neutral_pct", sa.Float(), nullable=False),
        sa.Column("concerned_pct", sa.Float(), nullable=False),
        sa.Column("confrontational_pct", sa.Float(), nullable=False),
        sa.Column("risk_event_count", sa.Integer(), nullable=False),
        sa.Column("top_countries_mentioned", sa.JSON(), nullable=True),
        sa.Column("top_topics", sa.Text(), nullable=True),
        sa.Column("ally_countries", sa.JSON(), nullable=True),
        sa.Column("adversary_countries", sa.JSON(), nullable=True),
        sa.Column("avg_sentence_length", sa.Float(), nullable=False),
        sa.Column("lexical_diversity", sa.Float(), nullable=False),
        sa.Column("diplo_vocab_score", sa.Float(), nullable=False),
        sa.Column("demand_count", sa.Integer(), nullable=False),
        sa.Column("pattern_diversity", sa.Float(), nullable=False),
        sa.Column("avg_hedging_score", sa.Float(), nullable=False),
        sa.Column("avg_politeness_ratio", sa.Float(), nullable=False),
        sa.Column("avg_dki_score", sa.Float(), nullable=False),
        sa.Column("dominant_frame", sa.Text(), nullable=True),
        sa.Column("dominant_audience", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["speaker_id"],
            ["speakers.speaker_id"],
        ),
        sa.PrimaryKeyConstraint("speaker_id"),
    )
    op.create_table(
        "topic_matrix",
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.PrimaryKeyConstraint("panel_id", "country", "topic"),
    )
    op.create_table(
        "ai_segment_insights",
        sa.Column("insight_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("seg_id", sa.String(), nullable=False),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("segment_summary", sa.Text(), nullable=True),
        sa.Column("strategy_analysis", sa.Text(), nullable=True),
        sa.Column("hidden_message", sa.Text(), nullable=True),
        sa.Column("power_dynamics", sa.Text(), nullable=True),
        sa.Column("impact_assessment", sa.Text(), nullable=True),
        sa.Column("consistency_score", sa.Float(), nullable=True),
        sa.Column("rhetoric_profile", sa.Text(), nullable=True),
        sa.Column("diplomatic_value", sa.Text(), nullable=True),
        sa.Column("sbi_analysis", sa.Text(), nullable=True),
        sa.Column("dki_analysis", sa.Text(), nullable=True),
        sa.Column("formula_inconsistency_score", sa.Float(), nullable=True),
        sa.Column("overall_logic_check", sa.Text(), nullable=True),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("pass_count", sa.Integer(), nullable=False),
        sa.Column("logic_health_pct", sa.Float(), nullable=True),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("insight_id"),
        sa.UniqueConstraint("seg_id"),
    )
    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.create_index("idx_seg_insight", ["seg_id"], unique=False)

    op.create_table(
        "country_references",
        sa.Column("ref_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("mention_count", sa.Integer(), nullable=False),
        sa.Column("sentiment_context", sa.Float(), nullable=True),
        sa.Column("context_snippet", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("ref_id"),
    )
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.create_index("idx_coref_from", ["from_country"], unique=False)
        batch_op.create_index("idx_coref_to", ["to_country"], unique=False)

    op.create_table(
        "risk_events",
        sa.Column("risk_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("sent_id", sa.Text(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("signal_phrase", sa.Text(), nullable=True),
        sa.Column("target_country", sa.Text(), nullable=True),
        sa.Column("severity", sa.Integer(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("risk_id"),
    )
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.create_index("idx_risk_country", ["from_country"], unique=False)

    op.create_table(
        "sentences",
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.Column("seg_id", sa.String(), nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("speaker_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("bloc", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("sent_order", sa.Integer(), nullable=True),
        sa.Column("global_sent_order", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("vader_compound", sa.Float(), nullable=False),
        sa.Column("diplo_compound", sa.Float(), nullable=False),
        sa.Column("emotion_category", sa.Text(), nullable=True),
        sa.Column("dominant_topic", sa.Text(), nullable=True),
        sa.Column("topic_scores", sa.JSON(), nullable=True),
        sa.Column("risk_signals", sa.JSON(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=False),
        sa.Column("entities_gpe", sa.JSON(), nullable=True),
        sa.Column("entities_person", sa.JSON(), nullable=True),
        sa.Column("demand_type", sa.Text(), nullable=True),
        sa.Column("demand_weight", sa.Float(), nullable=False),
        sa.Column("demand_category", sa.Text(), nullable=True),
        sa.Column("rhetoric_type", sa.Text(), nullable=True),
        sa.Column("influence_tier", sa.Text(), nullable=True),
        sa.Column("negation_aware_diplo", sa.Float(), nullable=False),
        sa.Column("topic_specificity", sa.Float(), nullable=False),
        sa.Column("hedging_score", sa.Float(), nullable=False),
        sa.Column("politeness_ratio", sa.Float(), nullable=False),
        sa.Column("face_threat_count", sa.Integer(), nullable=False),
        sa.Column("face_save_count", sa.Integer(), nullable=False),
        sa.Column("dominant_frame", sa.Text(), nullable=True),
        sa.Column("evidence_types", sa.JSON(), nullable=True),
        sa.Column("appraisal_attitude", sa.Text(), nullable=True),
        sa.Column("audience_type", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("sent_id"),
    )
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.create_index("idx_sent_audience", ["audience_type"], unique=False)
        batch_op.create_index("idx_sent_country", ["country"], unique=False)
        batch_op.create_index("idx_sent_demand", ["demand_type"], unique=False)
        batch_op.create_index("idx_sent_emotion", ["emotion_category"], unique=False)
        batch_op.create_index("idx_sent_frame", ["dominant_frame"], unique=False)
        batch_op.create_index("idx_sent_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_sent_rhetoric", ["rhetoric_type"], unique=False)
        batch_op.create_index("idx_sent_seg", ["seg_id"], unique=False)
        batch_op.create_index("idx_sent_speaker", ["speaker_id"], unique=False)
        batch_op.create_index("idx_sent_topic", ["dominant_topic"], unique=False)

    op.create_table(
        "ai_sentence_analysis",
        sa.Column("ai_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.Column("seg_id", sa.Text(), nullable=True),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("global_sent_order", sa.Integer(), nullable=True),
        sa.Column("prev_sent_id", sa.Text(), nullable=True),
        sa.Column("next_sent_id", sa.Text(), nullable=True),
        sa.Column("triplet_text", sa.Text(), nullable=True),
        sa.Column("sentiment_score", sa.Float(), nullable=True),
        sa.Column("sentiment_category", sa.Text(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("risk_level", sa.Text(), nullable=True),
        sa.Column("risk_description", sa.Text(), nullable=True),
        sa.Column("has_demand", sa.Boolean(), nullable=False),
        sa.Column("demand_type", sa.Text(), nullable=True),
        sa.Column("primary_topic", sa.Text(), nullable=True),
        sa.Column("secondary_topic", sa.Text(), nullable=True),
        sa.Column("diplomatic_tone", sa.Text(), nullable=True),
        sa.Column("intent_analysis", sa.Text(), nullable=True),
        sa.Column("manipulation_score", sa.Float(), nullable=True),
        sa.Column("has_inconsistency", sa.Boolean(), nullable=False),
        sa.Column("contextual_importance", sa.Text(), nullable=True),
        sa.Column("rhetorical_strategy", sa.Text(), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("subtext", sa.Text(), nullable=True),
        sa.Column("commentary", sa.Text(), nullable=True),
        sa.Column("hedging_score", sa.Float(), nullable=True),
        sa.Column("politeness_score", sa.Float(), nullable=True),
        sa.Column("framing", sa.Text(), nullable=True),
        sa.Column("evidence_type", sa.Text(), nullable=True),
        sa.Column("appraisal_attitude", sa.Text(), nullable=True),
        sa.Column("audience_type", sa.Text(), nullable=True),
        sa.Column("logic_check_sentiment", sa.Text(), nullable=True),
        sa.Column("logic_check_emotion", sa.Text(), nullable=True),
        sa.Column("logic_check_risk", sa.Text(), nullable=True),
        sa.Column("logic_check_demand", sa.Text(), nullable=True),
        sa.Column("logic_check_topic", sa.Text(), nullable=True),
        sa.Column("logic_check_hedging", sa.Text(), nullable=True),
        sa.Column("logic_check_frame", sa.Text(), nullable=True),
        sa.Column("logic_check_appraisal", sa.Text(), nullable=True),
        sa.Column("logic_check_audience", sa.Text(), nullable=True),
        sa.Column("logic_check_manipulation", sa.Text(), nullable=True),
        sa.Column("logic_check_politeness", sa.Text(), nullable=True),
        sa.Column("overall_logic_check", sa.Text(), nullable=True),
        sa.Column("logic_fail_reasons", sa.Text(), nullable=True),
        sa.Column("logic_pass_count", sa.Integer(), nullable=False),
        sa.Column("logic_fail_count", sa.Integer(), nullable=False),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("from_cache", sa.Boolean(), nullable=False),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("ai_id"),
        sa.UniqueConstraint("sent_id"),
    )
    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.create_index("idx_ai_country", ["country"], unique=False)
        batch_op.create_index("idx_ai_logic", ["overall_logic_check"], unique=False)
        batch_op.create_index("idx_ai_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_ai_risk", ["risk_level"], unique=False)
        batch_op.create_index("idx_ai_sent_id", ["sent_id"], unique=False)
        batch_op.create_index("idx_ai_tone", ["diplomatic_tone"], unique=False)

    op.create_table(
        "demand_records",
        sa.Column("demand_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("demand_verb", sa.Text(), nullable=False),
        sa.Column("demand_type", sa.Text(), nullable=False),
        sa.Column("demand_weight", sa.Float(), nullable=False),
        sa.Column("demand_category", sa.Text(), nullable=True),
        sa.Column("target_entity", sa.Text(), nullable=True),
        sa.Column("demand_topic", sa.Text(), nullable=True),
        sa.Column("full_sentence", sa.Text(), nullable=False),
        sa.Column("diplo_compound", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("demand_id"),
    )
    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.create_index("idx_demand_country", ["country"], unique=False)
        batch_op.create_index("idx_demand_type", ["demand_type"], unique=False)

    op.create_table(
        "panel_dynamics",
        sa.Column("dyn_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("kgi_score", sa.Float(), nullable=False),
        sa.Column("risk_delta", sa.Float(), nullable=False),
        sa.Column("emotion_shift", sa.Float(), nullable=False),
        sa.Column("topic_shift", sa.Integer(), nullable=False),
        sa.Column("inconsistency_score", sa.Float(), nullable=False),
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("dyn_id"),
    )
    with op.batch_alter_table("panel_dynamics", schema=None) as batch_op:
        batch_op.create_index("idx_dyn_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_dyn_sent", ["sent_id"], unique=True)

    op.create_table(
        "pattern_records",
        sa.Column("pattern_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=False),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("pattern_type", sa.Text(), nullable=False),
        sa.Column("pattern_text", sa.Text(), nullable=True),
        sa.Column("full_sentence", sa.Text(), nullable=False),
        sa.Column("dominant_topic", sa.Text(), nullable=True),
        sa.Column("diplo_compound", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("pattern_id"),
    )
    with op.batch_alter_table("pattern_records", schema=None) as batch_op:
        batch_op.create_index("idx_pattern_country", ["country"], unique=False)
        batch_op.create_index("idx_pattern_type", ["pattern_type"], unique=False)

    op.create_table(
        "words",
        sa.Column("word_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.Column("seg_id", sa.String(), nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("speaker_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("bloc", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("word_raw", sa.Text(), nullable=False),
        sa.Column("word_norm", sa.Text(), nullable=False),
        sa.Column("word_position", sa.Integer(), nullable=False),
        sa.Column("is_stopword", sa.Boolean(), nullable=False),
        sa.Column("diplo_score", sa.Float(), nullable=False),
        sa.Column("is_named_entity", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("word_id"),
    )
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.create_index("idx_word_country", ["country"], unique=False)
        batch_op.create_index("idx_word_norm", ["word_norm"], unique=False)
        batch_op.create_index("idx_word_seg", ["seg_id"], unique=False)
        batch_op.create_index("idx_word_stopword", ["is_stopword"], unique=False)

    op.create_table(
        "ai_demand_analysis",
        sa.Column("ai_demand_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("demand_id", sa.Integer(), nullable=True),
        sa.Column("sent_id", sa.String(), nullable=True),
        sa.Column("seg_id", sa.Text(), nullable=True),
        sa.Column("panel_id", sa.Text(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=False),
        sa.Column("demand_verb", sa.Text(), nullable=True),
        sa.Column("demand_type", sa.Text(), nullable=True),
        sa.Column("demand_category", sa.Text(), nullable=True),
        sa.Column("future_risk", sa.Text(), nullable=True),
        sa.Column("risk_severity", sa.Integer(), nullable=True),
        sa.Column("demand_subtext", sa.Text(), nullable=True),
        sa.Column("hidden_agenda", sa.Text(), nullable=True),
        sa.Column("potential_response", sa.Text(), nullable=True),
        sa.Column("escalation_path", sa.Text(), nullable=True),
        sa.Column("diplomatic_leverage", sa.Text(), nullable=True),
        sa.Column("future_demands", sa.Text(), nullable=True),
        sa.Column("strategic_value", sa.Float(), nullable=True),
        sa.Column("backend_used", sa.Text(), nullable=True),
        sa.Column("model_used", sa.Text(), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column(
            "processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["demand_id"],
            ["demand_records.demand_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sent_id"],
            ["sentences.sent_id"],
        ),
        sa.PrimaryKeyConstraint("ai_demand_id"),
    )
    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.create_index("idx_ai_demand_country", ["country"], unique=False)
        batch_op.create_index("idx_ai_demand_demand", ["demand_id"], unique=False)
        batch_op.create_index("idx_ai_demand_sent", ["sent_id"], unique=False)

    op.execute("PRAGMA journal_mode=WAL")
    op.execute("PRAGMA synchronous=NORMAL")
    op.execute("PRAGMA cache_size=10000")
    op.execute("PRAGMA temp_store=MEMORY")
    op.execute("PRAGMA foreign_keys=ON")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.drop_index("idx_ai_demand_sent")
        batch_op.drop_index("idx_ai_demand_demand")
        batch_op.drop_index("idx_ai_demand_country")

    op.drop_table("ai_demand_analysis")
    with op.batch_alter_table("words", schema=None) as batch_op:
        batch_op.drop_index("idx_word_stopword")
        batch_op.drop_index("idx_word_seg")
        batch_op.drop_index("idx_word_norm")
        batch_op.drop_index("idx_word_country")

    op.drop_table("words")
    with op.batch_alter_table("pattern_records", schema=None) as batch_op:
        batch_op.drop_index("idx_pattern_type")
        batch_op.drop_index("idx_pattern_country")

    op.drop_table("pattern_records")
    with op.batch_alter_table("panel_dynamics", schema=None) as batch_op:
        batch_op.drop_index("idx_dyn_sent")
        batch_op.drop_index("idx_dyn_panel")

    op.drop_table("panel_dynamics")
    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.drop_index("idx_demand_type")
        batch_op.drop_index("idx_demand_country")

    op.drop_table("demand_records")
    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.drop_index("idx_ai_tone")
        batch_op.drop_index("idx_ai_sent_id")
        batch_op.drop_index("idx_ai_risk")
        batch_op.drop_index("idx_ai_panel")
        batch_op.drop_index("idx_ai_logic")
        batch_op.drop_index("idx_ai_country")

    op.drop_table("ai_sentence_analysis")
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.drop_index("idx_sent_topic")
        batch_op.drop_index("idx_sent_speaker")
        batch_op.drop_index("idx_sent_seg")
        batch_op.drop_index("idx_sent_rhetoric")
        batch_op.drop_index("idx_sent_panel")
        batch_op.drop_index("idx_sent_frame")
        batch_op.drop_index("idx_sent_emotion")
        batch_op.drop_index("idx_sent_demand")
        batch_op.drop_index("idx_sent_country")
        batch_op.drop_index("idx_sent_audience")

    op.drop_table("sentences")
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index("idx_risk_country")

    op.drop_table("risk_events")
    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.drop_index("idx_coref_to")
        batch_op.drop_index("idx_coref_from")

    op.drop_table("country_references")
    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.drop_index("idx_seg_insight")

    op.drop_table("ai_segment_insights")
    op.drop_table("topic_matrix")
    op.drop_table("speaker_profiles")
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.drop_index("idx_seg_topic")
        batch_op.drop_index("idx_seg_panel")
        batch_op.drop_index("idx_seg_emotion")
        batch_op.drop_index("idx_seg_country")

    op.drop_table("segments")
    with op.batch_alter_table("discourse_network_edges", schema=None) as batch_op:
        batch_op.drop_index("idx_net_from")

    op.drop_table("discourse_network_edges")
    op.drop_table("country_stats")
    op.drop_table("ai_panel_synthesis")
    with op.batch_alter_table("ai_fail_anomaly_cross", schema=None) as batch_op:
        batch_op.drop_index("idx_fac_sent")
        batch_op.drop_index("idx_fac_fail")

    op.drop_table("ai_fail_anomaly_cross")
    op.drop_table("speakers")
    op.drop_table("panels")
    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.drop_index("idx_pair_from")

    op.drop_table("country_pair_sentiment")
    with op.batch_alter_table("ai_validation_log", schema=None) as batch_op:
        batch_op.drop_index("idx_val_type")
        batch_op.drop_index("idx_val_sent")
        batch_op.drop_index("idx_val_result")

    op.drop_table("ai_validation_log")
    with op.batch_alter_table("ai_fail_patterns", schema=None) as batch_op:
        batch_op.drop_index("idx_fail_pattern_kat")
        batch_op.drop_index("idx_fail_pattern_chk")

    op.drop_table("ai_fail_patterns")
    with op.batch_alter_table("ai_fail_cache", schema=None) as batch_op:
        batch_op.drop_index("idx_fcache_hash")

    op.drop_table("ai_fail_cache")
    with op.batch_alter_table("ai_fail_analysis", schema=None) as batch_op:
        batch_op.drop_index("idx_fail_sent")
        batch_op.drop_index("idx_fail_panel")
        batch_op.drop_index("idx_fail_kategori")
        batch_op.drop_index("idx_fail_country")
        batch_op.drop_index("idx_fail_check")

    op.drop_table("ai_fail_analysis")
    with op.batch_alter_table("ai_contextual_flags", schema=None) as batch_op:
        batch_op.drop_index("idx_flags_type")
        batch_op.drop_index("idx_flags_sev")
        batch_op.drop_index("idx_flags_sent")
        batch_op.drop_index("idx_flags_country")
        batch_op.drop_index("idx_flags_cat")

    op.drop_table("ai_contextual_flags")
    with op.batch_alter_table("ai_cache", schema=None) as batch_op:
        batch_op.drop_index("idx_cache_hash")

    op.drop_table("ai_cache")
    # ### end Alembic commands ###
