"""merge panels and processed_files into files

Revision ID: 84643356932b
Revises: 13b6b75a4194
Create Date: 2026-05-26 20:09:39.441555

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84643356932b"
down_revision: Union[str, None] = "13b6b75a4194"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Fetch and drop all views to avoid view validation errors on batch alter
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        views = bind.execute(
            sa.text("SELECT name, sql FROM sqlite_master WHERE type='view'")
        ).fetchall()
    else:
        raw_views = bind.execute(
            sa.text(
                "SELECT viewname, definition FROM pg_views WHERE schemaname = 'public'"
            )
        ).fetchall()
        views = [
            (name, f"CREATE VIEW {name} AS {definition}")
            for name, definition in raw_views
        ]
    view_defs = []
    for name, sql in views:
        if sql:
            op.execute(f"DROP VIEW IF EXISTS {name}")
            view_defs.append((name, sql))

    def get_fk_name(table_name: str, column_name: str, referred_table_name: str) -> str:
        if bind.dialect.name == "postgresql":
            return f"{table_name}_{column_name}_fkey"
        else:
            return f"fk_{table_name}_{column_name}_{referred_table_name}"

    naming_convention = {
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("file_id", sa.String(), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.Text(), nullable=False),
        sa.Column("parser_version", sa.Text(), nullable=True),
        sa.Column("speaker_map_version", sa.Text(), nullable=True),
        sa.Column(
            "first_processed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("last_processed_at", sa.DateTime(), nullable=True),
        sa.Column("reprocess_count", sa.Integer(), nullable=False),
        sa.Column("force_rebuild", sa.Integer(), nullable=False),
        sa.Column("file_name", sa.Text(), nullable=False),
        sa.Column("panel_number", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("inferred_theme", sa.Text(), nullable=True),
        sa.Column("date_str", sa.Text(), nullable=True),
        sa.Column("file_format", sa.Text(), nullable=False),
        sa.Column("file_hash", sa.Text(), nullable=True),
        sa.Column("n_segments", sa.Integer(), nullable=False),
        sa.Column("n_sentences", sa.Integer(), nullable=False),
        sa.Column("n_speakers", sa.Integer(), nullable=False),
        sa.Column("n_countries", sa.Integer(), nullable=False),
        sa.Column("total_words", sa.Integer(), nullable=False),
        sa.Column("total_duration_sec", sa.Integer(), nullable=False),
        sa.Column(
            "imported_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("file_id"),
        sa.UniqueConstraint("file_hash"),
        sa.UniqueConstraint("idempotency_key"),
    )
    # Table drops moved to the end of upgrade to avoid NoSuchTableError during reflection of other tables
    with op.batch_alter_table(
        "actor_action_matrix", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_matrix_panel"))
        batch_op.create_index("idx_matrix_panel", ["file_id"], unique=False)
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_contextual_flags", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Text(), nullable=True))
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_demand_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Text(), nullable=True))
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_fail_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f("idx_fail_panel"))
        batch_op.create_index("idx_fail_panel", ["file_id"], unique=False)
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_panel_synthesis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.create_unique_constraint("uq_ai_panel_synthesis_file_id", ["file_id"])
        batch_op.drop_constraint(
            get_fk_name("ai_panel_synthesis", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_ai_panel_synthesis_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_segment_insights", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Text(), nullable=True))
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_sentence_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Text(), nullable=True))
        batch_op.drop_index(batch_op.f("idx_ai_panel"))
        batch_op.create_index("idx_ai_panel", ["file_id"], unique=False)
        batch_op.create_index("idx_ai_processed_at", ["processed_at"], unique=False)
        batch_op.create_index(
            "idx_ai_prompt_processed", ["prompt_version", "processed_at"], unique=False
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "ai_validation_log", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.Text(), nullable=True))
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "analytics", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column(
            "topic_scores", existing_type=sqlite.JSON(), nullable=False
        )
        batch_op.alter_column(
            "topic_node_mapping", existing_type=sqlite.JSON(), nullable=False
        )

    with op.batch_alter_table(
        "country_stats", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.drop_constraint(
            get_fk_name("country_stats", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_country_stats_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "demand_records", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.drop_constraint(
            get_fk_name("demand_records", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_demand_records_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "dependency_triples", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f("idx_dep_panel"))
        batch_op.create_index("idx_dep_panel", ["file_id"], unique=False)
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "discourse_network_edges", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_index(batch_op.f("ix_net_actor"))
        batch_op.drop_index(batch_op.f("ix_net_session"))
        batch_op.drop_index(batch_op.f("ix_net_weight"))
        batch_op.create_index(
            batch_op.f("ix_discourse_network_edges_session_id"),
            ["session_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_discourse_network_edges_weight"), ["weight"], unique=False
        )
        batch_op.create_index(
            "ix_net_weight_high",
            ["weight"],
            unique=False,
            postgresql_where="weight > 0.5",
        )
        batch_op.drop_constraint(
            get_fk_name("discourse_network_edges", "panel_id", "panels"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_discourse_network_edges_panel_id_files",
            "files",
            ["panel_id"],
            ["file_id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table(
        "discourse_network_edges_legacy",
        schema=None,
        naming_convention=naming_convention,
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f("idx_net_legacy_from"))
        batch_op.create_index("idx_net_from", ["from_country"], unique=False)
        batch_op.drop_constraint(
            get_fk_name("discourse_network_edges_legacy", "panel_id", "panels"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_discourse_network_edges_legacy_file_id_files",
            "files",
            ["file_id"],
            ["file_id"],
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "human_reviews", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_index("idx_review_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "idx_review_status_created",
            ["agreement_status", "created_at"],
            unique=False,
        )

    with op.batch_alter_table(
        "legacy_country_references", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.drop_constraint(
            get_fk_name("legacy_country_references", "panel_id", "panels"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_legacy_country_references_file_id_files",
            "files",
            ["file_id"],
            ["file_id"],
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "panel_dynamics", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.drop_index(batch_op.f("idx_dyn_panel"))
        batch_op.create_index("idx_dyn_panel", ["file_id"], unique=False)
        batch_op.drop_constraint(
            get_fk_name("panel_dynamics", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_panel_dynamics_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "pattern_records", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.alter_column(
            "risk_score",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            get_fk_name("pattern_records", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_pattern_records_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "segments", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_seg_panel"))
        batch_op.create_index("idx_seg_file", ["file_id"], unique=False)
        batch_op.drop_constraint(
            get_fk_name("segments", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            get_fk_name("segments", "speaker_id", "speakers"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_segments_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.create_foreign_key(
            "fk_segments_speaker_id_speaker_profiles",
            "speaker_profiles",
            ["speaker_id"],
            ["speaker_id"],
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "sentences", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.drop_index(batch_op.f("idx_sent_panel"))
        batch_op.create_index("idx_sent_file", ["file_id"], unique=False)
        batch_op.drop_constraint(
            get_fk_name("sentences", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_sentences_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "speaker_profiles", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column(
            "total_duration_sec",
            existing_type=sa.INTEGER(),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.drop_constraint(
            get_fk_name("speaker_profiles", "speaker_id", "speakers"),
            type_="foreignkey",
        )

    with op.batch_alter_table(
        "topic_matrix", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.drop_constraint(
            get_fk_name("topic_matrix", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_topic_matrix_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "words", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=False))
        batch_op.drop_constraint(
            get_fk_name("words", "panel_id", "panels"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_words_file_id_files", "files", ["file_id"], ["file_id"]
        )
        batch_op.drop_column("panel_id")

    # Drop legacy/unused tables now that all alters are done and reflection won't fail
    op.drop_table("processed_files")
    with op.batch_alter_table(
        "ai_human_review_queue", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_index(batch_op.f("idx_review_panel"))
        batch_op.drop_index(batch_op.f("idx_review_status"))

    op.drop_table("ai_human_review_queue")
    op.drop_table("panels")
    op.drop_table("speakers")
    op.drop_table("drift_events")

    # Recreate all views, replacing panel_id with file_id
    for name, sql in view_defs:
        new_sql = sql.replace("panel_id", "file_id").replace("PANEL_ID", "FILE_ID")
        op.execute(new_sql)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Fetch and drop all views to avoid view validation errors on batch alter
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        views = bind.execute(
            sa.text("SELECT name, sql FROM sqlite_master WHERE type='view'")
        ).fetchall()
    else:
        raw_views = bind.execute(
            sa.text(
                "SELECT viewname, definition FROM pg_views WHERE schemaname = 'public'"
            )
        ).fetchall()
        views = [
            (name, f"CREATE VIEW {name} AS {definition}")
            for name, definition in raw_views
        ]
    view_defs = []
    for name, sql in views:
        if sql:
            op.execute(f"DROP VIEW IF EXISTS {name}")
            view_defs.append((name, sql))

    naming_convention = {
        "ix": "ix_%(column_0_label)s",
        "uq": "uq_%(table_name)s_%(column_0_name)s",
        "ck": "ck_%(table_name)s_%(constraint_name)s",
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
        "pk": "pk_%(table_name)s",
    }
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "words", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_words_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_words_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "topic_matrix", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_topic_matrix_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_topic_matrix_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "speaker_profiles", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_foreign_key(
            "fk_speaker_profiles_speaker_id_speakers",
            "speakers",
            ["speaker_id"],
            ["speaker_id"],
        )
        batch_op.alter_column(
            "total_duration_sec",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )

    with op.batch_alter_table(
        "sentences", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_sentences_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_sentences_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.drop_index("idx_sent_file")
        batch_op.create_index(batch_op.f("idx_sent_panel"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "segments", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_segments_file_id_files", type_="foreignkey")
        batch_op.drop_constraint(
            "fk_segments_speaker_id_speaker_profiles", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_segments_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.create_foreign_key(
            "fk_segments_speaker_id_speakers",
            "speakers",
            ["speaker_id"],
            ["speaker_id"],
        )
        batch_op.drop_index("idx_seg_file")
        batch_op.create_index(batch_op.f("idx_seg_panel"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "pattern_records", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("fk_pattern_records_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_pattern_records_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.alter_column(
            "risk_score",
            existing_type=sa.INTEGER(),
            server_default=sa.text("'0'"),
            existing_nullable=False,
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "panel_dynamics", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("fk_panel_dynamics_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_panel_dynamics_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.drop_index("idx_dyn_panel")
        batch_op.create_index(batch_op.f("idx_dyn_panel"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "legacy_country_references", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(
            "fk_legacy_country_references_file_id_files", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_legacy_country_references_panel_id_panels",
            "panels",
            ["panel_id"],
            ["panel_id"],
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "human_reviews", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_index("idx_review_status_created")
        batch_op.drop_index("idx_review_created_at")

    with op.batch_alter_table(
        "discourse_network_edges_legacy",
        schema=None,
        naming_convention=naming_convention,
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(
            "fk_discourse_network_edges_legacy_file_id_files", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_discourse_network_edges_legacy_panel_id_panels",
            "panels",
            ["panel_id"],
            ["panel_id"],
        )
        batch_op.drop_index("idx_net_from")
        batch_op.create_index(
            batch_op.f("idx_net_legacy_from"), ["from_country"], unique=False
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "discourse_network_edges", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint(
            "fk_discourse_network_edges_file_id_files", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_discourse_network_edges_panel_id_panels",
            "panels",
            ["panel_id"],
            ["panel_id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index("ix_net_weight_high", postgresql_where="weight > 0.5")
        batch_op.drop_index(batch_op.f("ix_discourse_network_edges_weight"))
        batch_op.drop_index(batch_op.f("ix_discourse_network_edges_session_id"))
        batch_op.create_index(batch_op.f("ix_net_weight"), ["weight"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_net_session"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_net_actor"), ["actor_id"], unique=False)

    with op.batch_alter_table(
        "dependency_triples", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_index("idx_dep_panel")
        batch_op.create_index(batch_op.f("idx_dep_panel"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "demand_records", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint("fk_demand_records_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_demand_records_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "country_stats", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint("fk_country_stats_file_id_files", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_country_stats_panel_id_panels", "panels", ["panel_id"], ["panel_id"]
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "analytics", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column(
            "topic_node_mapping", existing_type=sqlite.JSON(), nullable=True
        )
        batch_op.alter_column(
            "topic_scores", existing_type=sqlite.JSON(), nullable=True
        )

    with op.batch_alter_table(
        "ai_validation_log", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.TEXT(), nullable=True))
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_sentence_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.TEXT(), nullable=True))
        batch_op.drop_index("idx_ai_prompt_processed")
        batch_op.drop_index("idx_ai_processed_at")
        batch_op.drop_index("idx_ai_panel")
        batch_op.create_index(batch_op.f("idx_ai_panel"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_segment_insights", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.TEXT(), nullable=True))
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_panel_synthesis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(
            "fk_ai_panel_synthesis_file_id_files", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_ai_panel_synthesis_panel_id_panels",
            "panels",
            ["panel_id"],
            ["panel_id"],
        )
        batch_op.drop_constraint("uq_ai_panel_synthesis_file_id", type_="unique")
        batch_op.create_unique_constraint(
            "uq_ai_panel_synthesis_panel_id", ["panel_id"]
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_fail_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.TEXT(), nullable=True))
        batch_op.drop_index("idx_fail_panel")
        batch_op.create_index(batch_op.f("idx_fail_panel"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_demand_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.TEXT(), nullable=True))
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_contextual_flags", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.TEXT(), nullable=True))
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "actor_action_matrix", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(), nullable=False))
        batch_op.drop_index("idx_matrix_panel")
        batch_op.create_index(
            batch_op.f("idx_matrix_panel"), ["panel_id"], unique=False
        )
        batch_op.drop_column("file_id")

    op.drop_table("files")

    # Recreate all views, replacing file_id with panel_id
    for name, sql in view_defs:
        new_sql = sql.replace("file_id", "panel_id").replace("FILE_ID", "PANEL_ID")
        op.execute(new_sql)

    # ### end Alembic commands ###
