"""create_drift_events_table

Revision ID: 9042307bdc61
Revises: ff4c1efbc89e
Create Date: 2026-05-27 01:47:06.977556

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9042307bdc61"
down_revision: str | None = "ff4c1efbc89e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drift_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("speaker_id", sa.String(), nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("drift_type", sa.String(), nullable=False),
        sa.Column("start_position", sa.Integer(), nullable=False),
        sa.Column("end_position", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("before_state", sa.Text(), nullable=True),
        sa.Column("after_state", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("algorithm", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("drift_events")
    # ### end Alembic commands ###
