"""add formula validation logs table

Revision ID: a07b04be8ec8
Revises: 9153500a68a3
Create Date: 2026-05-26 14:52:31.278447

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a07b04be8ec8"
down_revision: str | None = "9153500a68a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "formula_validation_logs",
        sa.Column("log_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.String(), nullable=False),
        sa.Column("formula_name", sa.String(), nullable=False),
        sa.Column("expected_constraint", sa.Text(), nullable=False),
        sa.Column("actual_value", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("log_id"),
    )
    with op.batch_alter_table("formula_validation_logs", schema=None) as batch_op:
        batch_op.create_index(
            "idx_fval_entity", ["entity_type", "entity_id"], unique=False
        )
        batch_op.create_index("idx_fval_formula", ["formula_name"], unique=False)
        batch_op.create_index("idx_fval_run", ["run_id"], unique=False)
        batch_op.create_index("idx_fval_status", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("formula_validation_logs", schema=None) as batch_op:
        batch_op.drop_index("idx_fval_status")
        batch_op.drop_index("idx_fval_run")
        batch_op.drop_index("idx_fval_formula")
        batch_op.drop_index("idx_fval_entity")

    op.drop_table("formula_validation_logs")
    # ### end Alembic commands ###
