"""add_human_reviews_and_calibration_reports

Revision ID: b754aee19e42
Revises: 44785eb5dced
Create Date: 2026-05-18 14:30:05.594843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b754aee19e42"
down_revision: Union[str, None] = "44785eb5dced"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actor_action_matrix",
        sa.Column("matrix_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=False),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("verb", sa.Text(), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("is_passive_pct", sa.Float(), nullable=False),
        sa.Column("is_negative_pct", sa.Float(), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("matrix_id"),
    )
    with op.batch_alter_table("actor_action_matrix", schema=None) as batch_op:
        batch_op.create_index("idx_matrix_from", ["from_country"], unique=False)
        batch_op.create_index("idx_matrix_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_matrix_to", ["to_country"], unique=False)

    op.create_table(
        "ai_explanations",
        sa.Column("explanation_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.Column("risk_explanation", sa.Text(), nullable=False),
        sa.Column("sentiment_explanation", sa.Text(), nullable=False),
        sa.Column("grammatical_explanation", sa.Text(), nullable=True),
        sa.Column("discrepancy_explanation", sa.Text(), nullable=True),
        sa.Column("executive_summary", sa.Text(), nullable=False),
        sa.Column("token_attributions_json", sa.Text(), nullable=True),
        sa.Column(
            "generated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("explanation_id"),
    )
    with op.batch_alter_table("ai_explanations", schema=None) as batch_op:
        batch_op.create_index("idx_exp_sent", ["sent_id"], unique=False)

    op.create_table(
        "calibration_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("evaluation_period_start", sa.DateTime(), nullable=False),
        sa.Column("evaluation_period_end", sa.DateTime(), nullable=False),
        sa.Column("cohens_kappa_frame", sa.Float(), nullable=True),
        sa.Column("cohens_kappa_risk", sa.Float(), nullable=True),
        sa.Column("ai_human_f1_frame", sa.Float(), nullable=True),
        sa.Column("ai_human_f1_risk", sa.Float(), nullable=True),
        sa.Column("sbi_mae", sa.Float(), nullable=True),
        sa.Column("total_reviews", sa.Integer(), nullable=False),
        sa.Column("total_disagreements", sa.Integer(), nullable=False),
        sa.Column(
            "top_disagreement_patterns",
            sa.JSON(),
            nullable=True,
            comment="En sık anlaşmazlık patternları listesi",
        ),
        sa.Column("requires_prompt_update", sa.Boolean(), nullable=False),
        sa.Column("requires_weight_update", sa.Boolean(), nullable=False),
        sa.Column("alert_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calibration_reports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_calibration_reports_prompt_version"),
            ["prompt_version"],
            unique=False,
        )

    op.create_table(
        "dependency_triples",
        sa.Column("triple_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_id", sa.String(), nullable=False),
        sa.Column("seg_id", sa.String(), nullable=True),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("speaker_name", sa.Text(), nullable=True),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column("subject_raw", sa.Text(), nullable=True),
        sa.Column("subject_resolved", sa.Text(), nullable=True),
        sa.Column("verb_lemma", sa.Text(), nullable=True),
        sa.Column("object_raw", sa.Text(), nullable=True),
        sa.Column("object_resolved", sa.Text(), nullable=True),
        sa.Column("is_passive", sa.Integer(), nullable=False),
        sa.Column("is_negative", sa.Integer(), nullable=False),
        sa.Column("sentiment_context", sa.Float(), nullable=True),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("human_verified", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("triple_id"),
    )
    with op.batch_alter_table("dependency_triples", schema=None) as batch_op:
        batch_op.create_index("idx_dep_from", ["subject_resolved"], unique=False)
        batch_op.create_index("idx_dep_panel", ["panel_id"], unique=False)
        batch_op.create_index("idx_dep_sent", ["sent_id"], unique=False)
        batch_op.create_index("idx_dep_to", ["object_resolved"], unique=False)
        batch_op.create_index("idx_dep_verb", ["verb_lemma"], unique=False)

    op.create_table(
        "human_reviews",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "analysis_id",
            sa.String(length=36),
            nullable=False,
            comment="FK -> ai_sentence_analyses.id",
        ),
        sa.Column("reviewer_id", sa.String(length=100), nullable=False),
        sa.Column("ai_sbi_score", sa.Float(), nullable=True),
        sa.Column("ai_dominant_frame", sa.String(length=100), nullable=True),
        sa.Column("ai_risk_level", sa.String(length=20), nullable=True),
        sa.Column("ai_sentiment_score", sa.Float(), nullable=True),
        sa.Column("human_sbi_score", sa.Float(), nullable=True),
        sa.Column("human_dominant_frame", sa.String(length=100), nullable=True),
        sa.Column("human_risk_level", sa.String(length=20), nullable=True),
        sa.Column("human_sentiment_score", sa.Float(), nullable=True),
        sa.Column("agreement_status", sa.String(length=20), nullable=False),
        sa.Column("disagreement_reason", sa.Text(), nullable=True),
        sa.Column("review_duration_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("has_frame_disagreement", sa.Boolean(), nullable=True),
        sa.Column("has_risk_disagreement", sa.Boolean(), nullable=True),
        sa.Column("sbi_delta", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("human_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_human_reviews_analysis_id"), ["analysis_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_human_reviews_reviewer_id"), ["reviewer_id"], unique=False
        )

    op.create_table(
        "topic_assignments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("segment_id", sa.String(length=64), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("primary_topic", sa.String(length=64), nullable=False),
        sa.Column("topic_scores", sa.JSON(), nullable=False),
        sa.Column("topic_label", sa.String(length=255), nullable=True),
        sa.Column("ctfidf_keywords", sa.JSON(), nullable=False),
        sa.Column("model_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_topic_assignments_analysis_id"),
            ["analysis_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_topic_assignments_segment_id"), ["segment_id"], unique=False
        )

    op.create_table(
        "discourse_network_edges_legacy",
        sa.Column("edge_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("panel_id", sa.String(), nullable=True),
        sa.Column("from_country", sa.Text(), nullable=False),
        sa.Column("to_country", sa.Text(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("avg_sentiment", sa.Float(), nullable=False),
        sa.Column("edge_type", sa.Text(), nullable=True),
        sa.Column("power_source", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.PrimaryKeyConstraint("edge_id"),
    )
    with op.batch_alter_table(
        "discourse_network_edges_legacy", schema=None
    ) as batch_op:
        batch_op.create_index("idx_net_legacy_from", ["from_country"], unique=False)

    op.create_table(
        "discourse_flows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("from_country", sa.String(length=100), nullable=False),
        sa.Column("to_country", sa.String(length=100), nullable=False),
        sa.Column("edge_type", sa.String(length=50), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("sentiment_toward", sa.Float(), nullable=False),
        sa.Column("confrontational_count", sa.Integer(), nullable=False),
        sa.Column("cooperative_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("discourse_flows", schema=None) as batch_op:
        batch_op.create_index(
            "ix_df_from_to", ["from_country", "to_country"], unique=False
        )
        batch_op.create_index("ix_df_panel_id", ["panel_id"], unique=False)

    op.create_table(
        "topic_matrices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("panel_id", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("topic_scores", sqlite.JSON(), nullable=False),
        sa.Column("dominant_topic", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic_matrices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_tm_panel_country", ["panel_id", "country"], unique=True
        )

    op.create_table(
        "transcripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("speaker_name", sa.String(length=255), nullable=False),
        sa.Column("country_code", sa.String(length=10), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("vader_compound", sa.Float(), nullable=True),
        sa.Column("power_level", sa.Integer(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analytics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("transcript_id", sa.Integer(), nullable=False),
        sa.Column("sbi_score", sa.Float(), nullable=True),
        sa.Column("dki_score", sa.Float(), nullable=True),
        sa.Column("hedging_markers", sa.JSON(), nullable=False),
        sa.Column("framing_labels", sa.JSON(), nullable=False),
        sa.Column("raw_ai_output", sa.Text(), nullable=True),
        sa.Column("topic_scores", sa.JSON(), nullable=False),
        sa.Column("topic_node_mapping", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["transcript_id"],
            ["transcripts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ai_human_review_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_review_panel"))
        batch_op.drop_index(batch_op.f("idx_review_status"))

    op.drop_table("ai_human_review_queue")
    op.drop_table("processed_files")
    op.drop_table("drift_events")
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_risk_country"))

    op.drop_table("risk_events")
    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_insight", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_insight_version", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("insight_generated_at", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "coherence_score",
                sa.Float(),
                nullable=True,
                comment="DualGate consensus coherence score (0.0-1.0)",
            )
        )
        batch_op.add_column(
            sa.Column(
                "anomaly_consensus_level",
                sa.String(length=30),
                nullable=True,
                comment="CLEAN|SOFT_ANOMALY|HARD_ANOMALY|CRITICAL_ANOMALY",
            )
        )
        batch_op.add_column(
            sa.Column(
                "anomaly_ai_decision",
                sa.String(length=20),
                nullable=True,
                comment="CONFIRMED|DISMISSED|ESCALATED|AI_ONLY|INCONCLUSIVE",
            )
        )
        batch_op.add_column(
            sa.Column(
                "anomaly_ai_reasoning",
                sa.String(length=1000),
                nullable=True,
                comment="AI Anomaly Controller reasoning",
            )
        )
        batch_op.add_column(
            sa.Column(
                "anomaly_detected_subtype",
                sa.String(length=50),
                nullable=True,
                comment="irony|rhetorical_strategy|coercive_signal|tone_drift",
            )
        )
        batch_op.add_column(sa.Column("backend", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("model_name", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_sentiment", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_emotion", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_risk_score", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("ai_risk_level", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_demand_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_topic", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("ai_hedging_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_frame_type", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("ai_manipulation_score", sa.Float(), nullable=True)
        )
        batch_op.add_column(sa.Column("ai_politeness_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_evidence_type", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("logic_result", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("validation_flags", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("raw_response", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("tokens_used", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("latency_ms", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("anomaly_types", sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column("anomaly_severity", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "risk_level",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"
            ),
            existing_nullable=True,
        )
        batch_op.drop_index(batch_op.f("idx_ai_sent_prompt_ver"))

    with op.batch_alter_table("bilateral_sentiments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("vote_affinity", sa.Numeric(precision=12, scale=6), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "alliance_score", sa.Numeric(precision=12, scale=6), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "structural_distance", sa.Numeric(precision=12, scale=6), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "discourse_sentiment_delta",
                sa.Numeric(precision=12, scale=6),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "maoz_diplomatic_distance",
                sa.Numeric(precision=12, scale=6),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "maoz_affinity_score", sa.Numeric(precision=12, scale=6), nullable=True
            )
        )

    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.alter_column(
            "relationship_type",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "ALLY",
                "ADVERSARY",
                "PARTNER",
                "CAUTIOUS",
                "NEUTRAL",
                name="relationshiptype",
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.String(length=36), nullable=False))
        batch_op.add_column(
            sa.Column("speaker_country", sa.String(length=100), nullable=False)
        )
        batch_op.add_column(
            sa.Column("referenced_country", sa.String(length=100), nullable=False)
        )
        batch_op.add_column(sa.Column("sentence_index", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("reference_context", sa.String(length=50), nullable=False)
        )
        batch_op.add_column(
            sa.Column("raw_sentiment_score", sa.Float(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("speaker_power_level", sa.Float(), nullable=False)
        )
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.alter_column("panel_id", existing_type=sa.VARCHAR(), nullable=False)
        batch_op.drop_index(batch_op.f("idx_coref_from"))
        batch_op.drop_index(batch_op.f("idx_coref_to"))
        batch_op.create_index("ix_cr_panel_id", ["panel_id"], unique=False)
        batch_op.create_index(
            "ix_cr_speaker_referenced",
            ["speaker_country", "referenced_country"],
            unique=False,
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("context_snippet")
        batch_op.drop_column("mention_count")
        batch_op.drop_column("to_country")
        batch_op.drop_column("ref_id")
        batch_op.drop_column("seg_id")
        batch_op.drop_column("from_country")
        batch_op.drop_column("sentiment_context")

    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
        )

    with op.batch_alter_table("discourse_network_edges", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.add_column(
            sa.Column("session_id", sa.String(length=64), nullable=False)
        )
        batch_op.add_column(sa.Column("actor_id", sa.String(length=64), nullable=False))
        batch_op.add_column(
            sa.Column("concept_id", sa.String(length=64), nullable=False)
        )
        batch_op.add_column(
            sa.Column("tf", sa.Numeric(precision=12, scale=6), nullable=False)
        )
        batch_op.add_column(
            sa.Column("idf", sa.Numeric(precision=12, scale=6), nullable=False)
        )
        batch_op.add_column(
            sa.Column("segment_id", sa.String(length=64), nullable=True)
        )
        batch_op.alter_column(
            "weight",
            existing_type=sa.FLOAT(),
            type_=sa.Numeric(precision=12, scale=6),
            existing_nullable=False,
        )
        batch_op.drop_index(batch_op.f("idx_net_from"))
        batch_op.create_index(
            batch_op.f("ix_discourse_network_edges_session_id"),
            ["session_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_discourse_network_edges_weight"), ["weight"], unique=False
        )
        batch_op.create_index(
            "ix_net_weight_high",
            ["weight"],
            unique=False,
            postgresql_where="weight > 0.5",
        )
        batch_op.create_unique_constraint(
            "uq_network_edge_actor_concept", ["session_id", "actor_id", "concept_id"]
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "panels", ["panel_id"], ["panel_id"], ondelete="CASCADE"
        )
        batch_op.drop_column("avg_sentiment")
        batch_op.drop_column("edge_type")
        batch_op.drop_column("to_country")
        batch_op.drop_column("power_source")
        batch_op.drop_column("from_country")
        batch_op.drop_column("edge_id")

    with op.batch_alter_table("panels", schema=None) as batch_op:
        batch_op.drop_column("is_active")
        batch_op.drop_column("replaced_by_panel_id")

    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start_time", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("end_time", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("duration", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("ai_analyzed", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("logic_result", sa.Text(), nullable=True))
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.TEXT(),
            type_=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("logic_result")
        batch_op.drop_column("ai_analyzed")
        batch_op.drop_column("duration")
        batch_op.drop_column("end_time")
        batch_op.drop_column("start_time")

    with op.batch_alter_table("panels", schema=None) as batch_op:
        batch_op.add_column(sa.Column("replaced_by_panel_id", sa.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "is_active", sa.INTEGER(), server_default=sa.text("1"), nullable=True
            )
        )

    with op.batch_alter_table("discourse_network_edges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("edge_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("from_country", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("power_source", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("to_country", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("edge_type", sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column("avg_sentiment", sa.FLOAT(), nullable=False))
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "panels", ["panel_id"], ["panel_id"])
        batch_op.drop_constraint("uq_network_edge_actor_concept", type_="unique")
        batch_op.drop_index("ix_net_weight_high", postgresql_where="weight > 0.5")
        batch_op.drop_index(batch_op.f("ix_discourse_network_edges_weight"))
        batch_op.drop_index(batch_op.f("ix_discourse_network_edges_session_id"))
        batch_op.create_index(
            batch_op.f("idx_net_from"), ["from_country"], unique=False
        )
        batch_op.alter_column(
            "weight",
            existing_type=sa.Numeric(precision=12, scale=6),
            type_=sa.FLOAT(),
            existing_nullable=False,
        )
        batch_op.drop_column("segment_id")
        batch_op.drop_column("idf")
        batch_op.drop_column("tf")
        batch_op.drop_column("concept_id")
        batch_op.drop_column("actor_id")
        batch_op.drop_column("session_id")
        batch_op.drop_column("id")

    with op.batch_alter_table("demand_records", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("country_references", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sentiment_context", sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column("from_country", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("seg_id", sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column("ref_id", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("to_country", sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column("mention_count", sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column("context_snippet", sa.TEXT(), nullable=True))
        batch_op.create_foreign_key(None, "segments", ["seg_id"], ["seg_id"])
        batch_op.create_foreign_key(None, "panels", ["panel_id"], ["panel_id"])
        batch_op.drop_index("ix_cr_speaker_referenced")
        batch_op.drop_index("ix_cr_panel_id")
        batch_op.create_index(batch_op.f("idx_coref_to"), ["to_country"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_coref_from"), ["from_country"], unique=False
        )
        batch_op.alter_column("panel_id", existing_type=sa.VARCHAR(), nullable=True)
        batch_op.drop_column("created_at")
        batch_op.drop_column("speaker_power_level")
        batch_op.drop_column("raw_sentiment_score")
        batch_op.drop_column("reference_context")
        batch_op.drop_column("sentence_index")
        batch_op.drop_column("referenced_country")
        batch_op.drop_column("speaker_country")
        batch_op.drop_column("id")

    with op.batch_alter_table("country_pair_sentiment", schema=None) as batch_op:
        batch_op.alter_column(
            "relationship_type",
            existing_type=sa.Enum(
                "ALLY",
                "ADVERSARY",
                "PARTNER",
                "CAUTIOUS",
                "NEUTRAL",
                name="relationshiptype",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    with op.batch_alter_table("bilateral_sentiments", schema=None) as batch_op:
        batch_op.drop_column("maoz_affinity_score")
        batch_op.drop_column("maoz_diplomatic_distance")
        batch_op.drop_column("discourse_sentiment_delta")
        batch_op.drop_column("structural_distance")
        batch_op.drop_column("alliance_score")
        batch_op.drop_column("vote_affinity")

    with op.batch_alter_table("ai_sentence_analysis", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_ai_sent_prompt_ver"), ["prompt_version"], unique=False
        )
        batch_op.alter_column(
            "risk_level",
            existing_type=sa.Enum(
                "NONE", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
        batch_op.drop_column("created_at")
        batch_op.drop_column("anomaly_severity")
        batch_op.drop_column("anomaly_types")
        batch_op.drop_column("latency_ms")
        batch_op.drop_column("tokens_used")
        batch_op.drop_column("raw_response")
        batch_op.drop_column("validation_flags")
        batch_op.drop_column("logic_result")
        batch_op.drop_column("ai_evidence_type")
        batch_op.drop_column("ai_politeness_score")
        batch_op.drop_column("ai_manipulation_score")
        batch_op.drop_column("ai_frame_type")
        batch_op.drop_column("ai_hedging_score")
        batch_op.drop_column("ai_topic")
        batch_op.drop_column("ai_demand_type")
        batch_op.drop_column("ai_risk_level")
        batch_op.drop_column("ai_risk_score")
        batch_op.drop_column("ai_emotion")
        batch_op.drop_column("ai_sentiment")
        batch_op.drop_column("model_name")
        batch_op.drop_column("backend")
        batch_op.drop_column("anomaly_detected_subtype")
        batch_op.drop_column("anomaly_ai_reasoning")
        batch_op.drop_column("anomaly_ai_decision")
        batch_op.drop_column("anomaly_consensus_level")
        batch_op.drop_column("coherence_score")

    with op.batch_alter_table("ai_segment_insights", schema=None) as batch_op:
        batch_op.drop_column("insight_generated_at")
        batch_op.drop_column("ai_insight_version")
        batch_op.drop_column("ai_insight")

    with op.batch_alter_table("ai_demand_analysis", schema=None) as batch_op:
        batch_op.alter_column(
            "demand_category",
            existing_type=sa.Enum(
                "INSTITUTIONAL_REFORM",
                "SECURITY_ACTION",
                "ECONOMIC_COOPERATION",
                "HUMANITARIAN_RESPONSE",
                "DIPLOMATIC_ENGAGEMENT",
                "LEGAL_ACCOUNTABILITY",
                name="demandcategory",
            ),
            type_=sa.TEXT(),
            existing_nullable=True,
        )

    op.create_table(
        "risk_events",
        sa.Column("risk_id", sa.INTEGER(), nullable=False),
        sa.Column("panel_id", sa.VARCHAR(), nullable=True),
        sa.Column("seg_id", sa.VARCHAR(), nullable=True),
        sa.Column("sent_id", sa.TEXT(), nullable=True),
        sa.Column("from_country", sa.TEXT(), nullable=True),
        sa.Column("speaker_name", sa.TEXT(), nullable=True),
        sa.Column("power_level", sa.INTEGER(), nullable=False),
        sa.Column("signal_phrase", sa.TEXT(), nullable=True),
        sa.Column("target_country", sa.TEXT(), nullable=True),
        sa.Column("severity", sa.INTEGER(), nullable=True),
        sa.Column("context", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["panel_id"],
            ["panels.panel_id"],
        ),
        sa.ForeignKeyConstraint(
            ["seg_id"],
            ["segments.seg_id"],
        ),
        sa.PrimaryKeyConstraint("risk_id"),
    )
    with op.batch_alter_table("risk_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_risk_country"), ["from_country"], unique=False
        )

    op.create_table(
        "drift_events",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("speaker_id", sa.VARCHAR(), nullable=False),
        sa.Column("panel_id", sa.VARCHAR(), nullable=False),
        sa.Column("drift_type", sa.VARCHAR(), nullable=False),
        sa.Column("start_position", sa.INTEGER(), nullable=False),
        sa.Column("end_position", sa.INTEGER(), nullable=False),
        sa.Column("severity", sa.VARCHAR(), nullable=False),
        sa.Column("before_state", sa.TEXT(), nullable=True),
        sa.Column("after_state", sa.TEXT(), nullable=True),
        sa.Column("confidence", sa.INTEGER(), nullable=False),
        sa.Column("algorithm", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processed_files",
        sa.Column("file_hash", sa.VARCHAR(), nullable=False),
        sa.Column("file_name", sa.TEXT(), nullable=False),
        sa.Column("file_size_bytes", sa.INTEGER(), nullable=False),
        sa.Column("idempotency_key", sa.TEXT(), nullable=False),
        sa.Column("parser_version", sa.TEXT(), nullable=True),
        sa.Column("speaker_map_version", sa.TEXT(), nullable=True),
        sa.Column(
            "first_processed_at",
            sa.TEXT(),
            server_default=sa.text("(datetime('now'))"),
            nullable=True,
        ),
        sa.Column("last_processed_at", sa.TEXT(), nullable=True),
        sa.Column("reprocess_count", sa.INTEGER(), nullable=False),
        sa.Column("force_rebuild", sa.INTEGER(), nullable=False),
        sa.PrimaryKeyConstraint("file_hash"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_table(
        "ai_human_review_queue",
        sa.Column("review_id", sa.INTEGER(), nullable=False),
        sa.Column("sent_id", sa.VARCHAR(), nullable=False),
        sa.Column("seg_id", sa.TEXT(), nullable=True),
        sa.Column("panel_id", sa.TEXT(), nullable=True),
        sa.Column("speaker_name", sa.TEXT(), nullable=True),
        sa.Column("country", sa.TEXT(), nullable=True),
        sa.Column("trigger_type", sa.VARCHAR(), nullable=False),
        sa.Column("ai_risk_score", sa.INTEGER(), nullable=True),
        sa.Column("anomaly_types", sa.TEXT(), nullable=True),
        sa.Column("uncertainty_score", sa.INTEGER(), nullable=True),
        sa.Column(
            "status", sa.VARCHAR(), server_default=sa.text("(PENDING)"), nullable=True
        ),
        sa.Column("assigned_to", sa.TEXT(), nullable=True),
        sa.Column("reviewer_notes", sa.TEXT(), nullable=True),
        sa.Column("original_ai_json", sa.TEXT(), nullable=False),
        sa.Column("corrected_json", sa.TEXT(), nullable=True),
        sa.Column(
            "flagged_at",
            sa.TEXT(),
            server_default=sa.text("(datetime('now'))"),
            nullable=True,
        ),
        sa.Column("reviewed_at", sa.TEXT(), nullable=True),
        sa.Column("review_duration_sec", sa.INTEGER(), nullable=True),
        sa.PrimaryKeyConstraint("review_id"),
    )
    with op.batch_alter_table("ai_human_review_queue", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("idx_review_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("idx_review_panel"), ["panel_id"], unique=False
        )

    op.drop_table("analytics")
    op.drop_table("transcripts")
    with op.batch_alter_table("topic_matrices", schema=None) as batch_op:
        batch_op.drop_index("ix_tm_panel_country")

    op.drop_table("topic_matrices")
    with op.batch_alter_table("discourse_flows", schema=None) as batch_op:
        batch_op.drop_index("ix_df_panel_id")
        batch_op.drop_index("ix_df_from_to")

    op.drop_table("discourse_flows")
    with op.batch_alter_table(
        "discourse_network_edges_legacy", schema=None
    ) as batch_op:
        batch_op.drop_index("idx_net_legacy_from")

    op.drop_table("discourse_network_edges_legacy")
    with op.batch_alter_table("topic_assignments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_assignments_segment_id"))
        batch_op.drop_index(batch_op.f("ix_topic_assignments_analysis_id"))

    op.drop_table("topic_assignments")
    with op.batch_alter_table("human_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_human_reviews_reviewer_id"))
        batch_op.drop_index(batch_op.f("ix_human_reviews_analysis_id"))

    op.drop_table("human_reviews")
    with op.batch_alter_table("dependency_triples", schema=None) as batch_op:
        batch_op.drop_index("idx_dep_verb")
        batch_op.drop_index("idx_dep_to")
        batch_op.drop_index("idx_dep_sent")
        batch_op.drop_index("idx_dep_panel")
        batch_op.drop_index("idx_dep_from")

    op.drop_table("dependency_triples")
    with op.batch_alter_table("calibration_reports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_calibration_reports_prompt_version"))

    op.drop_table("calibration_reports")
    with op.batch_alter_table("ai_explanations", schema=None) as batch_op:
        batch_op.drop_index("idx_exp_sent")

    op.drop_table("ai_explanations")
    with op.batch_alter_table("actor_action_matrix", schema=None) as batch_op:
        batch_op.drop_index("idx_matrix_to")
        batch_op.drop_index("idx_matrix_panel")
        batch_op.drop_index("idx_matrix_from")

    op.drop_table("actor_action_matrix")
    # ### end Alembic commands ###
