"""add entities_org to sentences

Revision ID: c448fa8484f5
Revises: 0b434cd674fe
Create Date: 2026-06-01 23:53:34.243989

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c448fa8484f5"
down_revision: str | None = "0b434cd674fe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("entities_org", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sentences", schema=None) as batch_op:
        batch_op.drop_column("entities_org")

    # ### end Alembic commands ###
