"""add_audit_entries_table

Revision ID: f2626f5f3e19
Revises: 36457cd3ec1c
Create Date: 2026-06-03 21:00:14.036673

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f2626f5f3e19"
down_revision: Union[str, None] = "36457cd3ec1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "audit_entries" not in tables:
        op.create_table(
            "audit_entries",
            sa.Column("audit_id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("action_type", sa.String(length=50), nullable=False),
            sa.Column("entity_type", sa.String(length=50), nullable=False),
            sa.Column(
                "performed_at",
                sa.DateTime(),
                server_default=sa.text("(CURRENT_TIMESTAMP)"),
                nullable=False,
            ),
            sa.Column("details", sa.JSON(), nullable=False),
            sa.PrimaryKeyConstraint("audit_id"),
        )

    if conn.dialect.name == "postgresql":
        with op.batch_alter_table("sentences", schema=None) as batch_op:
            batch_op.alter_column(
                "embedding",
                existing_type=sa.NUMERIC(precision=384),
                type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
                existing_nullable=True,
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        with op.batch_alter_table("sentences", schema=None) as batch_op:
            batch_op.alter_column(
                "embedding",
                existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
                type_=sa.NUMERIC(precision=384),
                existing_nullable=True,
            )

    op.drop_table("audit_entries")
    # ### end Alembic commands ###
