"""rename_panel_id_to_file_id_in_country_and_network_tables

Revision ID: ff4c1efbc89e
Revises: 84643356932b
Create Date: 2026-05-26 20:27:51.473211

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff4c1efbc89e"
down_revision: Union[str, None] = "84643356932b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    # Fetch and drop all views to avoid view validation errors on batch alter
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        views = bind.execute(
            sa.text("SELECT name, sql FROM sqlite_master WHERE type='view'")
        ).fetchall()
    else:
        raw_views = bind.execute(
            sa.text(
                "SELECT viewname, definition FROM pg_views WHERE schemaname = 'public'"
            )
        ).fetchall()
        views = [
            (name, f"CREATE VIEW {name} AS {definition}")
            for name, definition in raw_views
        ]
    view_defs = []
    for name, sql in views:
        if sql:
            op.execute(f"DROP VIEW IF EXISTS {name}")
            view_defs.append((name, sql))

    def get_uq_name(table_name: str, column_name: str) -> str:
        if bind.dialect.name == "postgresql":
            return f"{table_name}_{column_name}_key"
        else:
            return f"uq_{table_name}_{column_name}"

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "ai_sentence_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.drop_constraint(
            get_uq_name("ai_sentence_analysis", "sent_id"), type_="unique"
        )

    with op.batch_alter_table(
        "bilateral_sentiments", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f("ix_bs_panel_pair"))
        batch_op.create_index(
            "ix_bs_panel_pair", ["file_id", "from_country", "to_country"], unique=True
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "country_references", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f("ix_cr_panel_id"))
        batch_op.create_index("ix_cr_panel_id", ["file_id"], unique=False)
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "discourse_flows", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f("ix_df_panel_id"))
        batch_op.create_index("ix_df_panel_id", ["file_id"], unique=False)
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "discourse_network_edges", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(), nullable=True))
        batch_op.drop_constraint(
            "fk_discourse_network_edges_panel_id_files", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_discourse_network_edges_file_id_files",
            "files",
            ["file_id"],
            ["file_id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("panel_id")

    with op.batch_alter_table(
        "topic_matrices", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("file_id", sa.String(length=255), nullable=False))
        batch_op.drop_index(batch_op.f("ix_tm_panel_country"))
        batch_op.create_index(
            "ix_tm_panel_country", ["file_id", "country"], unique=True
        )
        batch_op.drop_column("panel_id")

    # Recreate all views, replacing panel_id with file_id
    for name, sql in view_defs:
        new_sql = sql.replace("panel_id", "file_id").replace("PANEL_ID", "FILE_ID")
        op.execute(new_sql)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Fetch and drop all views to avoid view validation errors on batch alter
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        views = bind.execute(
            sa.text("SELECT name, sql FROM sqlite_master WHERE type='view'")
        ).fetchall()
    else:
        raw_views = bind.execute(
            sa.text(
                "SELECT viewname, definition FROM pg_views WHERE schemaname = 'public'"
            )
        ).fetchall()
        views = [
            (name, f"CREATE VIEW {name} AS {definition}")
            for name, definition in raw_views
        ]
    view_defs = []
    for name, sql in views:
        if sql:
            op.execute(f"DROP VIEW IF EXISTS {name}")
            view_defs.append((name, sql))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "topic_matrices", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(
            sa.Column("panel_id", sa.VARCHAR(length=255), nullable=False)
        )
        batch_op.drop_index("ix_tm_panel_country")
        batch_op.create_index(
            batch_op.f("ix_tm_panel_country"), ["panel_id", "country"], unique=1
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "discourse_network_edges", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column("panel_id", sa.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(
            "fk_discourse_network_edges_file_id_files", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_discourse_network_edges_panel_id_files",
            "files",
            ["panel_id"],
            ["file_id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "discourse_flows", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(
            sa.Column("panel_id", sa.VARCHAR(length=255), nullable=False)
        )
        batch_op.drop_index("ix_df_panel_id")
        batch_op.create_index(batch_op.f("ix_df_panel_id"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "country_references", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(
            sa.Column("panel_id", sa.VARCHAR(length=255), nullable=False)
        )
        batch_op.drop_index("ix_cr_panel_id")
        batch_op.create_index(batch_op.f("ix_cr_panel_id"), ["panel_id"], unique=False)
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "bilateral_sentiments", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(
            sa.Column("panel_id", sa.VARCHAR(length=255), nullable=False)
        )
        batch_op.drop_index("ix_bs_panel_pair")
        batch_op.create_index(
            batch_op.f("ix_bs_panel_pair"),
            ["panel_id", "from_country", "to_country"],
            unique=1,
        )
        batch_op.drop_column("file_id")

    with op.batch_alter_table(
        "ai_sentence_analysis", schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_ai_sentence_analysis_sent_id"), ["sent_id"]
        )

    # Recreate all views, replacing file_id with panel_id
    for name, sql in view_defs:
        new_sql = sql.replace("file_id", "panel_id").replace("FILE_ID", "PANEL_ID")
        op.execute(new_sql)

    # ### end Alembic commands ###
