export interface CountryMeta {
  id: string;
  name: string;
  lat: number;
  lon: number;
  block: string;
  power: number;
  influence: number;
  stability: number;
  risk: number;
  gdp: number;
}

export const COUNTRIES: CountryMeta[] = [
  {
    id: 'TUR',
    name: 'Türkiye',
    lat: 39.0,
    lon: 35.0,
    block: 'ASIA',
    power: 7.2,
    influence: 6.8,
    stability: 5.5,
    risk: 6.1,
    gdp: 850,
  },
  {
    id: 'USA',
    name: 'ABD',
    lat: 38.0,
    lon: -97.0,
    block: 'WEST',
    power: 9.8,
    influence: 9.5,
    stability: 8.2,
    risk: 3.4,
    gdp: 23000,
  },
  {
    id: 'RUS',
    name: 'Rusya',
    lat: 61.5,
    lon: 105.3,
    block: 'EAST',
    power: 8.5,
    influence: 7.9,
    stability: 4.1,
    risk: 8.2,
    gdp: 1800,
  },
  {
    id: 'CHN',
    name: 'Çin',
    lat: 35.0,
    lon: 105.0,
    block: 'EAST',
    power: 9.1,
    influence: 8.4,
    stability: 7.5,
    risk: 5.8,
    gdp: 17700,
  },
  {
    id: 'DEU',
    name: 'Almanya',
    lat: 51.0,
    lon: 10.0,
    block: 'WEST',
    power: 7.8,
    influence: 8.1,
    stability: 8.5,
    risk: 2.9,
    gdp: 4200,
  },
  {
    id: 'FRA',
    name: 'Fransa',
    lat: 46.0,
    lon: 2.0,
    block: 'WEST',
    power: 7.1,
    influence: 7.5,
    stability: 6.8,
    risk: 4.2,
    gdp: 2900,
  },
  {
    id: 'GBR',
    name: 'İngiltere',
    lat: 54.0,
    lon: -2.0,
    block: 'WEST',
    power: 7.0,
    influence: 7.3,
    stability: 7.2,
    risk: 3.8,
    gdp: 3100,
  },
  {
    id: 'IRN',
    name: 'İran',
    lat: 32.0,
    lon: 53.0,
    block: 'ASIA',
    power: 5.8,
    influence: 5.2,
    stability: 3.1,
    risk: 9.1,
    gdp: 400,
  },
  {
    id: 'ISR',
    name: 'İsrail',
    lat: 31.0,
    lon: 34.8,
    block: 'ASIA',
    power: 6.2,
    influence: 5.5,
    stability: 5.0,
    risk: 8.8,
    gdp: 480,
  },
  {
    id: 'SAU',
    name: 'Suudi Arabistan',
    lat: 24.0,
    lon: 45.0,
    block: 'ASIA',
    power: 6.5,
    influence: 6.1,
    stability: 6.0,
    risk: 6.5,
    gdp: 1100,
  },
  {
    id: 'IND',
    name: 'Hindistan',
    lat: 22.0,
    lon: 79.0,
    block: 'ASIA',
    power: 7.5,
    influence: 6.5,
    stability: 6.2,
    risk: 5.5,
    gdp: 3500,
  },
  {
    id: 'BRA',
    name: 'Brezilya',
    lat: -14.2,
    lon: -51.9,
    block: 'GLOBAL_SOUTH',
    power: 5.5,
    influence: 4.8,
    stability: 5.8,
    risk: 5.2,
    gdp: 1900,
  },
  {
    id: 'ZAF',
    name: 'Güney Afrika',
    lat: -30.0,
    lon: 22.0,
    block: 'GLOBAL_SOUTH',
    power: 4.8,
    influence: 4.2,
    stability: 4.5,
    risk: 6.8,
    gdp: 420,
  },
  {
    id: 'JPN',
    name: 'Japonya',
    lat: 36.0,
    lon: 138.0,
    block: 'WEST',
    power: 7.3,
    influence: 6.9,
    stability: 8.8,
    risk: 3.1,
    gdp: 4900,
  },
  {
    id: 'KOR',
    name: 'Güney Kore',
    lat: 36.5,
    lon: 127.9,
    block: 'WEST',
    power: 6.8,
    influence: 6.2,
    stability: 7.8,
    risk: 4.5,
    gdp: 1800,
  },
];
