from enum import StrEnum


class DynamicEvent(StrEnum):
    ESCALATION_SPIKE = "ESCALATION_SPIKE"
    DE_ESCALATION = "DE_ESCALATION"
    TOPIC_SHIFT = "TOPIC_SHIFT"
    EMOTION_REVERSAL = "EMOTION_REVERSAL"
    STABLE = "STABLE"
