from enum import StrEnum


class PressureTier(StrEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"

    HIGH_PRESSURE = "HIGH_PRESSURE"
    MEDIUM_PRESSURE = "MEDIUM_PRESSURE"
    LOW_PRESSURE = "LOW_PRESSURE"
    DECLARATIVE = "DECLARATIVE"
