from enum import StrEnum


class TensionLevel(StrEnum):
    EXTREME_TENSION = "EXTREME_TENSION"
    HIGH_TENSION = "HIGH_TENSION"
    MODERATE_TENSION = "MODERATE_TENSION"
    LOW_TENSION = "LOW_TENSION"
