name: BB-PAXDATA CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          version: 2.0.1


      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-v2-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}


      - name: Install dependencies
        run: poetry install --no-interaction



      - name: Run Linting
        run: |
          poetry run ruff check src/
          poetry run black --check src/
          poetry run mypy src/

      - name: Run Tests
        run: |
          poetry run pytest tests/ --cov=src/bb_paxdata --cov-report=xml